#!/usr/bin/env python3
"""Batch 2: 50 entries — dumbbell (25) + bands (25) for Tweens/Teens."""
import json,os
SRC=os.path.join(os.path.dirname(__file__),'..','data','exercises.json')
SN=("MET values estimated from Compendium of Physical Activities (Ainsworth 2011) "
    "and NSCA Youth Resistance Training Guidelines; weight assumed 55 kg (Tweens/Teens).")
def ex(d):
    wt=d.get('wt',55);met=d.get('met',4.0);dur=d.get('dur',1.0)
    cpm=round(met*wt/60,1);ce=round(cpm*dur,1)
    role=d.get('pr','strength');pres=d.get('pres',{'sets':3,'reps':10,'rest_seconds':45,'tempo':'controlled'})
    eq=d.get('eq',['dumbbell'])
    return {
        "id":d['id'],"slug":d['slug'],"name":d['name'],"description":d['desc'],
        "level":d.get('level','Beginner'),"primary_focus":d.get('focus','Strength'),
        "body_area":None,"equipment":eq,
        "primary_muscles":d.get('pm',[]),"secondary_muscles":d.get('sm',[]),
        "stabilizer_muscles":d.get('st',[]),"muscles_subregions":d.get('sub',[]),
        "movement_pattern":d['mp'],"family":d.get('fam',d['slug']),
        "difficulty_rank":d.get('dr',2),"workout_roles":d.get('roles',['main']),
        "sports":d.get('sports',[]),"goals":d.get('goals',['build_strength','improve_performance']),
        "settings":d.get('settings',['home','gym']),
        "tags":d.get('tags',['strength','equipment_needed']),
        "contraindications":d.get('contra',[]),
        "narration_script":None,"popularity":None,"variant_of":None,
        "instructions":{"form":d.get('form',['Perform the movement with controlled tempo.']),"proTips":d.get('tips',[]),"commonMistakes":d.get('mistakes',[])},
        "classification":{"family":d.get('fam',d['slug']),"isPerSide":d.get('ps',False),
            "unilateral":d.get('uni',False),"energySystem":d.get('es','glycolytic'),
            "kineticChain":d.get('kc','closed'),"planeOfMotion":d.get('plane',['sagittal']),
            "bodyweightOnly":False,"difficultyRank":d.get('dr',2),"movementPattern":d['mp'],
            "contractionTypes":d.get('ct',['concentric','eccentric']),
            "compoundOrIsolation":d.get('ci','compound')},
        "demands":{"cns":d.get('cns','medium'),"noise":d.get('noise','quiet'),
            "space":d.get('space','low'),"stability":d.get('stab','medium')},
        "prescription":{"isHold":d.get('hold',False),"default":{role:pres},"defaultHoldSeconds":d.get('hs',None)},
        "energy":{"metValue":met,"sourceNote":SN,"durationMinutes":dur,
            "caloriesEstimate":ce,"caloriesPerMinute":cpm,"assumedUserWeightKg":wt,"proteinPostWorkoutG":None},
        "timing":{"repSecondsEstimate":d.get('rs',None),"videoPortraitSeconds":None,"videoLandscapeSeconds":None},
        "media":{"image":{"path":None,"available":False},"videoPortrait":{"path":None,"available":False},"videoLandscape":{"path":None,"available":False}},
        "cv":None,"alternatives":[],"_raw":None,
        "taxonomy":{"age_bands_suggested":d.get('bands',["Tweens","Teens"]),"age_bands_confirmed":None,
            "sports_suggested":d.get('ts',[]),"sports_confirmed":None,
            "position":[],"position_confirmed":None,
            "movement_type":d.get('mt','strength'),"difficulty":d.get('diff','beginner'),
            "structure":d.get('struct','main'),"safety_flags":d.get('flags',[])},
        "review_status":"pending"}

TT=["Tweens","Teens"]

DEFS=[
# ── 25 DUMBBELL ───────────────────────────────────────────────────────────────
dict(id="kids-ex-0118",slug="dumbbell-romanian-deadlift",name="Dumbbell Romanian Deadlift",
    desc="A hip-hinge posterior chain exercise using dumbbells held in front of the thighs — developing hamstring and glute strength with a neutral spine, foundational for athletic jumping and sprinting.",
    focus="Strength",pm=["hamstrings","glutes"],sm=["back","core"],st=["calves"],
    sub=["biceps femoris","gluteus maximus","erector spinae"],
    mp="hip_extension",fam="romanian-deadlift",dr=2,eq=["dumbbell"],
    roles=["main"],goals=["build_legs","improve_performance","build_glutes"],
    tags=["strength","dumbbell","posterior_chain","athletic"],
    form=["Hold a dumbbell in each hand at thigh height, feet hip-width.",
          "Push your hips back and lower the dumbbells along your shins, keeping back flat.",
          "Lower until you feel a strong hamstring stretch (usually just below the knee).",
          "Drive hips forward to return, squeezing glutes at the top."],
    tips=["Think 'hips back' not 'chest down' — the hinge is from the hip."],
    mistakes=["Rounding the lower back — maintain a neutral spine throughout."],
    ts=["running","soccer","football","basketball"],mt="strength",diff="beginner",struct="main",
    met=4.5,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0119",slug="dumbbell-single-arm-row",name="Dumbbell Single Arm Row",
    desc="A unilateral horizontal pulling movement using one dumbbell and a bench or knee for support — building lat, rhomboid, and rear delt strength essential for throwing, serving, and pulling sport patterns.",
    focus="Strength",pm=["back"],sm=["biceps","rear_delts"],st=["core"],
    sub=["latissimus dorsi","rhomboids","posterior deltoid"],
    mp="pull_horizontal",fam="dumbbell-rows",dr=2,eq=["dumbbell"],
    ps=True,uni=True,roles=["main"],goals=["build_back","improve_posture","improve_performance"],
    tags=["strength","dumbbell","back","unilateral","pulling"],
    form=["Place your right hand and right knee on a bench; left foot flat on floor.",
          "Hold a dumbbell in your left hand, arm straight toward the floor.",
          "Row the dumbbell up toward your lower ribcage, elbow skimming close to your body.",
          "Lower slowly and repeat. Switch sides after all reps."],
    tips=["Drive the elbow back, not just the hand — lead with the elbow."],
    mistakes=["Rotating the torso — keep hips and shoulders square."],
    ts=["baseball","tennis","basketball","boxing"],mt="strength",diff="beginner",struct="main",
    met=4.0,pres={"sets":3,"reps":10,"rest_seconds":45,"tempo":"controlled"},rs=3.5),

dict(id="kids-ex-0120",slug="dumbbell-goblet-squat",name="Dumbbell Goblet Squat",
    desc="A front-loaded squat holding a single dumbbell vertically at chest height — an excellent teaching tool for squat depth, upright torso position, and knee tracking in young athletes.",
    focus="Strength",pm=["quads","glutes"],sm=["hamstrings","core","adductors"],st=["calves"],
    sub=["vastus lateralis","gluteus maximus","adductors"],
    mp="squat",fam="goblet-squat",dr=2,eq=["dumbbell"],
    roles=["main"],goals=["build_legs","improve_mobility","improve_performance"],
    tags=["strength","dumbbell","squat","beginner_friendly","lower_body"],
    form=["Hold one dumbbell vertically at chest height with both hands under the top plate.",
          "Stand with feet slightly wider than hip-width, toes turned out 15–30 degrees.",
          "Squat down, keeping elbows inside your knees — drive the knees out.",
          "Lower until thighs are parallel or below, then press through heels to stand."],
    tips=["Use the dumbbell as a counterbalance — it makes staying upright easier."],
    mistakes=["Letting knees cave in — actively push them out over the toes."],
    ts=["basketball","football","soccer","baseball"],mt="strength",diff="beginner",struct="main",
    met=5.0,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0121",slug="dumbbell-single-leg-rdl",name="Dumbbell Single-Leg RDL",
    desc="A unilateral hip-hinge exercise where athletes balance on one leg while lowering a dumbbell — combining posterior chain strength with single-leg balance and proprioception critical in all field sports.",
    focus="Strength",pm=["hamstrings","glutes"],sm=["back","core"],st=["calves","ankles"],
    sub=["gluteus maximus","erector spinae","gastrocnemius"],
    mp="hip_extension",fam="single-leg-rdl",dr=3,eq=["dumbbell"],
    ps=True,uni=True,roles=["main"],goals=["build_legs","improve_balance","improve_performance"],
    tags=["strength","dumbbell","unilateral","posterior_chain","balance"],
    form=["Hold a dumbbell in your right hand and stand on your left foot.",
          "Hinge forward, extending the right leg behind you as the dumbbell lowers.",
          "Keep the back flat and hips square — form a T-shape at the bottom.",
          "Drive through the left heel to return upright. Complete all reps then switch."],
    tips=["Keep the hip of the raised leg from rotating outward — square the hips down."],
    mistakes=["Rounding the lower back — hinge with a neutral spine."],
    ts=["running","soccer","football","basketball","tennis"],mt="strength",diff="intermediate",struct="main",
    met=4.5,pres={"sets":3,"reps":8,"rest_seconds":60,"tempo":"slow"},rs=4.0),

dict(id="kids-ex-0122",slug="dumbbell-floor-press",name="Dumbbell Floor Press",
    desc="A chest press performed lying on the floor with dumbbells — limiting shoulder range to a safe arc while building pectoral and tricep strength, ideal for athletes without a bench.",
    focus="Strength",pm=["chest"],sm=["triceps","shoulders"],st=["core"],
    sub=["pectoralis major","triceps brachii","anterior deltoid"],
    mp="push_horizontal",fam="chest-press-variations",dr=2,eq=["dumbbell"],
    roles=["main"],goals=["build_chest","build_upper_body","improve_performance"],
    tags=["strength","dumbbell","chest","floor_based","no_bench"],
    form=["Lie on your back with knees bent, holding a dumbbell in each hand at chest level.",
          "Press both dumbbells up to arm extension directly over your chest.",
          "Lower slowly until your upper arms touch the floor — that's the end range.",
          "Press back up to the start."],
    tips=["The floor prevents over-lowering, making this safer for young athletes."],
    mistakes=["Flaring elbows out to 90 degrees — keep them at 45 degrees to the body."],
    ts=["boxing","basketball","baseball","football"],mt="strength",diff="beginner",struct="main",
    met=4.5,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=3.5),

dict(id="kids-ex-0123",slug="dumbbell-bent-over-row",name="Dumbbell Bent Over Row",
    desc="A bilateral horizontal row with the torso hinged at 45 degrees — pulling both dumbbells simultaneously to build upper back thickness and rowing strength, key for posture and athletic pulling power.",
    focus="Strength",pm=["back"],sm=["biceps","rear_delts","core"],st=["hamstrings"],
    sub=["latissimus dorsi","rhomboids","trapezius"],
    mp="pull_horizontal",fam="dumbbell-rows",dr=2,eq=["dumbbell"],
    roles=["main"],goals=["build_back","improve_posture","improve_performance"],
    tags=["strength","dumbbell","back","compound","bilateral"],
    form=["Hold a dumbbell in each hand, hinge forward at hips until torso is at ~45 degrees.",
          "Let dumbbells hang straight down from your shoulders.",
          "Row both dumbbells simultaneously toward your lower ribs.",
          "Squeeze shoulder blades at the top. Lower slowly."],
    tips=["Initiate with the shoulder blades — retract before you pull with the arms."],
    mistakes=["Jerking with the lower back — keep the hinge position still throughout."],
    ts=["baseball","tennis","boxing","basketball"],mt="strength",diff="beginner",struct="main",
    met=4.5,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=3.5),

dict(id="kids-ex-0124",slug="dumbbell-sumo-squat",name="Dumbbell Sumo Squat",
    desc="A wide-stance squat holding one dumbbell between the legs — emphasising the inner thighs, glutes, and hips more than a standard squat, excellent for developing lateral hip strength for field sports.",
    focus="Strength",pm=["quads","glutes","adductors"],sm=["hamstrings","core"],st=["calves"],
    sub=["adductors","gluteus maximus","vastus medialis"],
    mp="squat",fam="squat-variations",dr=1,eq=["dumbbell"],
    roles=["main"],goals=["build_legs","improve_mobility","improve_performance"],
    tags=["strength","dumbbell","squat","inner_thigh","beginner_friendly"],
    form=["Hold one dumbbell vertically with both hands, hanging between your legs.",
          "Stand with feet wider than shoulder width, toes turned out 45 degrees.",
          "Lower straight down, keeping the dumbbell between your knees.",
          "Drive through heels to stand, squeezing glutes at top."],
    tips=["The wider stance makes it more adductor-focused — really push knees out."],
    mistakes=["Knees caving in — push them outward in line with the toes."],
    ts=["basketball","soccer","football","baseball"],mt="strength",diff="beginner",struct="main",
    met=5.0,pres={"sets":3,"reps":12,"rest_seconds":45,"tempo":"controlled"},rs=3.5),

dict(id="kids-ex-0125",slug="dumbbell-overhead-press",name="Dumbbell Overhead Press",
    desc="A bilateral vertical pressing movement with dumbbells from shoulder height to full extension overhead — building shoulder and tricep strength essential for overhead sports, volleyball spikes, and throwing.",
    focus="Strength",pm=["shoulders"],sm=["triceps","core","back"],st=["calves"],
    sub=["anterior deltoid","medial deltoid","triceps brachii"],
    mp="push_vertical",fam="overhead-press",dr=2,eq=["dumbbell"],
    roles=["main"],goals=["build_shoulders","build_upper_body","improve_performance"],
    tags=["strength","dumbbell","shoulders","overhead","compound"],
    form=["Sit or stand with a dumbbell in each hand at shoulder height, palms forward.",
          "Press both dumbbells up and slightly inward until arms are fully extended.",
          "Lower slowly back to shoulder height — that is one rep."],
    tips=["Keep your core braced — don't arch the lower back as you press overhead."],
    mistakes=["Pressing forward (in front of the face) instead of straight up."],
    ts=["tennis","baseball","basketball","volleyball"],mt="strength",diff="beginner",struct="main",
    met=4.5,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=3.5),

dict(id="kids-ex-0126",slug="dumbbell-hip-thrust",name="Dumbbell Hip Thrust",
    desc="A glute-dominant hip extension exercise with a dumbbell resting on the hips, upper back on a bench — the gold-standard glute builder for power, speed, and injury prevention in young athletes.",
    focus="Strength",pm=["glutes"],sm=["hamstrings","core"],st=["back"],
    sub=["gluteus maximus","hamstring proximal","erector spinae"],
    mp="hip_extension",fam="glute-bridges",dr=2,eq=["dumbbell"],
    roles=["main"],goals=["build_glutes","build_legs","improve_performance"],
    tags=["strength","dumbbell","glutes","posterior_chain","athletic"],
    form=["Sit on the floor with upper back against a bench. Place a dumbbell across your hips.",
          "Plant feet hip-width, knees bent.",
          "Drive hips up until body is flat from knees to shoulders.",
          "Squeeze glutes hard at the top for 1 second. Lower slowly."],
    tips=["Tuck your chin to chest to keep your spine neutral at the top."],
    mistakes=["Hyperextending the lower back — stop when the body is flat, not arched."],
    ts=["running","soccer","football","basketball"],mt="strength",diff="beginner",struct="main",
    met=4.5,pres={"sets":3,"reps":12,"rest_seconds":60,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0127",slug="dumbbell-reverse-lunge",name="Dumbbell Reverse Lunge",
    desc="A rear-stepping lunge holding dumbbells at the sides — lower knee-stress than forward lunges while equally targeting the quad and glute, making it ideal for young athletes building unilateral leg strength.",
    focus="Strength",pm=["quads","glutes"],sm=["hamstrings","calves","core"],st=["ankles"],
    sub=["vastus lateralis","gluteus maximus","rectus femoris"],
    mp="squat",fam="lunge-variations",dr=2,eq=["dumbbell"],
    ps=True,uni=True,roles=["main"],goals=["build_legs","improve_balance","improve_performance"],
    tags=["strength","dumbbell","lunge","unilateral","lower_body"],
    form=["Hold a dumbbell in each hand at your sides, standing tall.",
          "Step your right foot straight back and lower the right knee toward the floor.",
          "Front (left) shin stays vertical, chest stays tall.",
          "Push through the left heel to return. Alternate legs or complete all reps one side."],
    tips=["Keep the front shin as vertical as possible — this protects the knee."],
    mistakes=["Leaning forward — stay upright and hinge slightly from the hips."],
    ts=["basketball","soccer","football","running"],mt="strength",diff="beginner",struct="main",
    met=5.0,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0128",slug="dumbbell-lateral-step-squat",name="Dumbbell Lateral Step Squat",
    desc="A lateral step into a squat holding dumbbells — combining frontal-plane movement with loaded squatting to build inner-thigh, glute, and quad strength specifically for cutting and lateral court movements.",
    focus="Strength",pm=["glutes","quads","adductors"],sm=["hamstrings","core"],st=["calves"],
    sub=["gluteus medius","adductors","vastus medialis"],
    mp="squat",fam="squat-variations",dr=2,eq=["dumbbell"],
    roles=["main"],goals=["build_legs","improve_agility","improve_performance"],
    tags=["strength","dumbbell","lateral","squat","agility"],
    form=["Hold a dumbbell in each hand at your sides.",
          "Step your right foot wide to the right and lower into a lateral squat.",
          "Push off the right foot to return to standing.",
          "Repeat all reps to the right, then switch to stepping left."],
    tips=["Sit into the hip of the stepping leg, not just the knee."],
    mistakes=["Caving the knee inward on landing."],
    ts=["basketball","soccer","football","tennis"],mt="strength",diff="beginner",struct="main",
    met=5.0,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=3.5),

dict(id="kids-ex-0129",slug="dumbbell-pullover",name="Dumbbell Pullover",
    desc="A lying chest and lat exercise where one dumbbell is lowered behind the head with straight arms — expanding the thoracic cage and building lat and pectoral strength important for swimming, throwing, and serve mechanics.",
    focus="Strength",pm=["chest","back"],sm=["triceps","shoulders","core"],st=[],
    sub=["pectoralis major","latissimus dorsi","serratus anterior"],
    mp="pull_vertical",fam="pullover-variations",dr=2,eq=["dumbbell"],
    roles=["main"],goals=["build_chest","build_back","improve_mobility"],
    tags=["strength","dumbbell","chest","lats","upper_body"],
    form=["Lie on your back on a bench (or floor) holding one dumbbell with both hands above your chest.",
          "Keeping arms slightly bent, lower the dumbbell in an arc behind your head.",
          "Feel the stretch across your chest and lats.",
          "Reverse the arc to bring the dumbbell back above your chest."],
    tips=["Keep a slight bend in the elbows throughout — never lock them straight."],
    mistakes=["Lowering too fast — control the eccentric for maximum stretch."],
    ts=["baseball","tennis","basketball"],mt="strength",diff="beginner",struct="main",
    met=4.0,pres={"sets":3,"reps":12,"rest_seconds":60,"tempo":"slow"},rs=4.0),

dict(id="kids-ex-0130",slug="dumbbell-upright-row",name="Dumbbell Upright Row",
    desc="A vertical pulling movement drawing dumbbells up the front of the body to chin height — building upper trapezius and lateral deltoid strength important for overhead and throwing athletes.",
    focus="Strength",pm=["shoulders","back"],sm=["biceps","core"],st=[],
    sub=["lateral deltoid","upper trapezius","supraspinatus"],
    mp="pull_vertical",fam="shoulder-pulls",dr=2,eq=["dumbbell"],
    roles=["main"],goals=["build_shoulders","build_upper_body","improve_performance"],
    tags=["strength","dumbbell","shoulders","upper_back","compound"],
    form=["Hold a dumbbell in each hand in front of your thighs, palms facing your body.",
          "Pull both dumbbells straight up, leading with the elbows.",
          "Elbows should travel higher than the dumbbells and flare outward.",
          "Lower slowly to start."],
    tips=["Lead with the elbows — they should be the highest point at the top."],
    mistakes=["Pulling too high (above chin level) — this risks shoulder impingement."],
    ts=["baseball","tennis","swimming","boxing"],mt="strength",diff="intermediate",struct="main",
    met=4.5,pres={"sets":3,"reps":12,"rest_seconds":60,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0131",slug="dumbbell-staggered-rdl",name="Dumbbell Staggered-Stance RDL",
    desc="A Romanian deadlift with one foot slightly ahead of the other — a stepping-stone between the bilateral RDL and the full single-leg version, building posterior chain strength with enhanced balance demand.",
    focus="Strength",pm=["hamstrings","glutes"],sm=["back","core"],st=["calves","ankles"],
    sub=["biceps femoris","gluteus maximus","erector spinae"],
    mp="hip_extension",fam="romanian-deadlift",dr=2,eq=["dumbbell"],
    ps=True,roles=["main"],goals=["build_legs","improve_balance","improve_performance"],
    tags=["strength","dumbbell","posterior_chain","balance","progression"],
    form=["Hold a dumbbell in each hand. Step your right foot 15–20 cm behind the left.",
          "Hinge at the hips, lowering dumbbells along the left shin.",
          "Feel the load shift more to the left hamstring and glute.",
          "Drive hips forward to stand. Complete all reps then switch stance."],
    tips=["70% of your weight is on the front foot — front leg drives the movement."],
    mistakes=["Treating it like a normal RDL — intentionally load the front leg."],
    ts=["running","soccer","football","basketball"],mt="strength",diff="beginner",struct="main",
    met=4.5,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0132",slug="dumbbell-alternating-curl",name="Dumbbell Alternating Bicep Curl",
    desc="An alternating arm bicep curl with a supinating wrist action — building elbow flexor strength and neuromuscular control relevant for pulling, throwing deceleration, and racket control.",
    focus="Strength",pm=["biceps"],sm=["forearms","shoulders"],st=["core"],
    sub=["biceps brachii","brachialis","brachioradialis"],
    mp="isolation",fam="bicep-curl-variations",dr=1,eq=["dumbbell"],
    roles=["main"],goals=["build_arms","improve_performance"],
    tags=["strength","dumbbell","biceps","isolation","beginner_friendly"],
    form=["Hold a dumbbell in each hand at your sides, palms facing inward (hammer grip).",
          "Curl the right dumbbell upward, rotating the palm upward as you lift.",
          "Lower slowly, then curl the left. Alternate for all reps."],
    tips=["Supinate (rotate palm up) at the top for full bicep contraction."],
    mistakes=["Swinging the body — keep the elbow pinned to your side."],
    ts=["baseball","tennis","boxing"],mt="strength",diff="beginner",struct="main",
    met=3.5,pres={"sets":3,"reps":12,"rest_seconds":45,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0133",slug="dumbbell-hip-hinge-row",name="Dumbbell Hip Hinge Row",
    desc="A hinge-position compound pull where athletes hold the hip hinge and perform a bent-over row — training posterior chain endurance and upper back strength simultaneously in an athletic position.",
    focus="Strength",pm=["back","hamstrings"],sm=["glutes","biceps","core"],st=[],
    sub=["latissimus dorsi","erector spinae","rhomboids"],
    mp="pull_horizontal",fam="dumbbell-rows",dr=3,eq=["dumbbell"],
    roles=["main"],goals=["build_back","build_legs","improve_performance"],
    tags=["strength","dumbbell","compound","back","posterior_chain","athletic"],
    form=["Hold dumbbells, hinge at hips to 45 degrees, back flat — hold this position throughout.",
          "Row both dumbbells to your lower ribs.",
          "Lower. Do 10 rows without coming out of the hinge.",
          "Stand, rest, reset."],
    tips=["The challenge here is the hinge isometric — fight to keep the back position."],
    mistakes=["Standing up between reps — the whole set is done in the hinged position."],
    ts=["baseball","tennis","boxing","basketball"],mt="strength",diff="intermediate",struct="main",
    met=5.0,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0134",slug="dumbbell-farmer-carry-stationary",name="Dumbbell Farmer Carry (Stationary)",
    desc="A loaded standing hold with heavy dumbbells — the 'stationary farmer's carry' trains grip, forearm, core, and shoulder girdle endurance without needing a long walkway, ideal for developing work capacity.",
    focus="Strength",pm=["forearms","core"],sm=["shoulders","back","quads"],st=["calves"],
    sub=["finger flexors","erector spinae","trapezius"],
    mp="hold",fam="carry-variations",dr=1,eq=["dumbbell"],
    hold=True,hs=30,roles=["main"],goals=["build_grip","improve_endurance","improve_posture"],
    tags=["strength","dumbbell","grip","functional","isometric"],
    form=["Hold a heavy dumbbell in each hand at your sides.",
          "Stand tall with shoulders back, core braced.",
          "Hold the position for the prescribed time — don't let the dumbbells pull you down.",
          "If walking is possible, walk 20 paces back and forth."],
    tips=["Squeeze the dumbbell handles hard — it improves whole-body tension."],
    mistakes=["Letting shoulders shrug or round — maintain proud posture."],
    ts=["baseball","football","rugby"],mt="strength",diff="beginner",struct="main",
    met=3.5,pres={"sets":3,"duration_seconds":30,"rest_seconds":45,"tempo":"static"},rs=30.0),

dict(id="kids-ex-0135",slug="dumbbell-lateral-raise",name="Dumbbell Lateral Raise",
    desc="An isolation deltoid exercise raising dumbbells to shoulder height with straight arms — directly targeting the medial deltoid for shoulder width and stability relevant for tennis, baseball, and overhead sports.",
    focus="Strength",pm=["shoulders"],sm=["core","back"],st=[],
    sub=["medial deltoid","supraspinatus"],
    mp="isolation",fam="shoulder-isolation",dr=1,eq=["dumbbell"],
    roles=["main"],goals=["build_shoulders","improve_posture","improve_performance"],
    tags=["strength","dumbbell","shoulders","isolation","medial_deltoid"],
    form=["Hold a dumbbell in each hand at your sides, palms facing inward.",
          "With a slight bend in the elbows, raise both arms out to the sides.",
          "Stop when arms are parallel to the floor (shoulder height).",
          "Lower slowly with control."],
    tips=["Lead with the pinky finger — slightly internally rotate for better medial delt engagement."],
    mistakes=["Swinging or shrugging — raise with only the deltoid, no momentum."],
    ts=["tennis","baseball","boxing","swimming"],mt="strength",diff="beginner",struct="main",
    met=3.5,pres={"sets":3,"reps":12,"rest_seconds":45,"tempo":"slow"},rs=3.0),

dict(id="kids-ex-0136",slug="dumbbell-step-up-curl",name="Dumbbell Step-Up with Curl",
    desc="A compound movement combining a step-up with a simultaneous bicep curl — developing unilateral leg strength and arm strength together in a functional movement pattern used in court and field sports.",
    focus="Strength",pm=["quads","glutes","biceps"],sm=["hamstrings","calves","shoulders"],st=["core"],
    sub=["vastus lateralis","gluteus maximus","biceps brachii"],
    mp="squat",fam="step-up-variations",dr=2,eq=["dumbbell"],
    ps=True,uni=True,roles=["main"],goals=["build_legs","build_arms","improve_coordination"],
    tags=["strength","dumbbell","compound","step_up","functional"],
    form=["Hold a dumbbell in each hand at your sides. Stand facing a step.",
          "Step up with your right foot, driving through the heel to stand on the step.",
          "As you step up, curl both dumbbells to your shoulders.",
          "Lower back down, lowering the dumbbells simultaneously. Switch lead foot each set."],
    tips=["The curl and the step should be synchronised — one fluid movement."],
    mistakes=["Curling first then stepping — start both together."],
    ts=["basketball","soccer","football"],mt="strength",diff="intermediate",struct="main",
    met=5.5,pres={"sets":3,"reps":8,"rest_seconds":60,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0137",slug="dumbbell-wood-chop",name="Dumbbell Wood Chop",
    desc="A rotational core exercise using one dumbbell held in both hands, chopping diagonally from high to low — directly training transverse-plane trunk power for golf swings, tennis groundstrokes, and baseball batting.",
    focus="Strength",pm=["core"],sm=["shoulders","glutes","back"],st=["quads"],
    sub=["obliques","transversus abdominis","anterior deltoid"],
    mp="rotation",fam="rotational-core",dr=2,eq=["dumbbell"],
    ps=True,roles=["main"],goals=["build_core","improve_performance","improve_rotation"],
    tags=["strength","dumbbell","rotational","core","sport_specific"],
    form=["Hold one dumbbell with both hands above your right shoulder.",
          "Rotate your torso and chop the dumbbell diagonally down toward your left knee.",
          "Allow your right heel to pivot as you rotate.",
          "Return the dumbbell to the start and repeat. Switch sides after all reps."],
    tips=["Generate power from the hips and core, not just the arms."],
    mistakes=["Chopping with arms only — drive the rotation from the pelvis."],
    ts=["golf","tennis","baseball","boxing"],mt="strength",diff="intermediate",struct="main",
    met=5.0,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0138",slug="dumbbell-front-squat",name="Dumbbell Front Squat",
    desc="A squat with dumbbells held at shoulder height in the front rack position — maintaining an upright torso through increased thoracic demand, building quad dominance and core strength for athletic performance.",
    focus="Strength",pm=["quads","core"],sm=["glutes","hamstrings","shoulders"],st=["calves"],
    sub=["rectus femoris","vastus medialis","anterior deltoid"],
    mp="squat",fam="squat-variations",dr=3,eq=["dumbbell"],
    roles=["main"],goals=["build_legs","build_core","improve_performance"],
    tags=["strength","dumbbell","squat","front_loaded","quad_dominant"],
    form=["Hold a dumbbell in each hand at shoulder level, elbows pointing forward.",
          "Keep elbows up throughout the entire squat.",
          "Squat to parallel or below, maintaining an upright chest.",
          "Drive through heels and maintain elbow height on the way up."],
    tips=["Elbows pointing forward is essential — dropping them rounds the upper back."],
    mistakes=["Lowering the elbows as fatigue sets in — fight to keep them up."],
    ts=["basketball","football","soccer","baseball"],mt="strength",diff="intermediate",struct="main",
    met=5.5,pres={"sets":3,"reps":8,"rest_seconds":60,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0139",slug="dumbbell-renegade-row",name="Dumbbell Renegade Row",
    desc="A plank-position rowing movement alternating dumbbell rows while holding the plank — building rotational core stability, shoulder strength, and anti-rotation control essential for throwing and hitting athletes.",
    focus="Strength",pm=["core","back"],sm=["shoulders","chest","biceps"],st=["wrists","glutes"],
    sub=["obliques","latissimus dorsi","serratus anterior"],
    mp="pull_horizontal",fam="dumbbell-rows",dr=3,eq=["dumbbell"],
    ps=True,roles=["main"],goals=["build_core","build_back","improve_performance"],
    tags=["strength","dumbbell","core","anti_rotation","compound","advanced_beginner"],
    form=["Start in a high plank with hands gripping dumbbells, shoulder-width apart.",
          "Row your right dumbbell up to your right hip, keeping hips square to the floor.",
          "Lower it and row the left dumbbell.",
          "Keep hips still throughout — don't let them rotate."],
    tips=["Wide feet make balancing easier — start wide, then feet closer as you improve."],
    mistakes=["Rotating the hips as you row — the whole point is anti-rotation."],
    ts=["baseball","tennis","boxing","golf"],mt="strength",diff="intermediate",struct="main",
    met=5.0,pres={"sets":3,"reps":8,"rest_seconds":60,"tempo":"slow"},rs=5.0),

dict(id="kids-ex-0140",slug="dumbbell-incline-rear-delt-row",name="Dumbbell Incline Rear Delt Row",
    desc="A prone incline bench row targeting the posterior deltoid and lower trapezius — one of the most important shoulder-health exercises for young overhead athletes in tennis, baseball, and swimming.",
    focus="Strength",pm=["shoulders","back"],sm=["biceps","core"],st=[],
    sub=["posterior deltoid","lower trapezius","rhomboids"],
    mp="pull_horizontal",fam="rear-delt-exercises",dr=2,eq=["dumbbell"],
    roles=["main"],goals=["build_shoulders","improve_posture","injury_prevention"],
    tags=["strength","dumbbell","rear_delt","posture","shoulder_health","overhead_sports"],
    form=["Lie face-down on an incline bench (or floor propped on folded mat) with a dumbbell in each hand.",
          "Let arms hang straight down.",
          "Pull both dumbbells up and out to the sides with elbows bent at 90 degrees — like a W shape.",
          "Squeeze the shoulder blades and rear delts at the top. Lower slowly."],
    tips=["Lead with the elbows and squeeze the rear delts — don't just lift with biceps."],
    mistakes=["Shrugging the traps — keep shoulders packed down."],
    ts=["baseball","tennis","boxing","swimming","golf"],mt="strength",diff="beginner",struct="main",
    met=3.5,pres={"sets":3,"reps":12,"rest_seconds":45,"tempo":"slow"},rs=4.0),

dict(id="kids-ex-0141",slug="dumbbell-pallof-press-lateral",name="Dumbbell Lateral Anti-Rotation Hold",
    desc="A dumbbell core stability exercise where athletes hold one dumbbell extended from the chest at arm's length — the weight creates a rotational demand the core must resist, training anti-rotation stability.",
    focus="Strength",pm=["core"],sm=["shoulders","back"],st=["quads","glutes"],
    sub=["obliques","transversus abdominis","anterior deltoid"],
    mp="anti_extension",fam="anti-rotation-core",dr=2,eq=["dumbbell"],
    hold=True,hs=20,ps=True,roles=["main"],goals=["build_core","improve_performance"],
    tags=["strength","dumbbell","anti_rotation","core","stability"],
    form=["Stand sideways to a wall or in open space. Hold one dumbbell at chest with both hands.",
          "Press the dumbbell straight out to arm's length.",
          "Hold for the prescribed time — resist the urge to rotate toward the weight.",
          "Lower, turn around, repeat on the other side."],
    tips=["Brace your core as if absorbing a punch — that tension prevents rotation."],
    mistakes=["Letting the torso rotate toward the weight."],
    ts=["golf","tennis","baseball","boxing"],mt="strength",diff="intermediate",struct="main",
    met=3.0,pres={"sets":3,"duration_seconds":20,"rest_seconds":45,"tempo":"static"},rs=20.0),

dict(id="kids-ex-0142",slug="dumbbell-tricep-kickback",name="Dumbbell Tricep Kickback",
    desc="A hinge-position elbow extension isolation exercise — one arm at a time, extending the dumbbell behind the body to lockout — targeting the tricep for throwing follow-through, pushing, and punch extension speed.",
    focus="Strength",pm=["triceps"],sm=["shoulders","core"],st=["back"],
    sub=["triceps brachii long head","lateral head"],
    mp="isolation",fam="tricep-exercises",dr=1,eq=["dumbbell"],
    ps=True,uni=True,roles=["main"],goals=["build_arms","improve_performance"],
    tags=["strength","dumbbell","triceps","isolation","beginner_friendly"],
    form=["Hinge forward at 45 degrees. Hold a dumbbell in your right hand, right elbow bent 90 degrees.",
          "Keeping your elbow pinned to your side, extend the forearm back until the arm is straight.",
          "Squeeze the tricep at full extension. Lower slowly.",
          "Complete all reps, then switch arms."],
    tips=["The upper arm stays completely still — only the forearm moves."],
    mistakes=["Swinging the upper arm down to help — pin it in place."],
    ts=["baseball","tennis","boxing"],mt="strength",diff="beginner",struct="main",
    met=3.5,pres={"sets":3,"reps":12,"rest_seconds":45,"tempo":"controlled"},rs=3.0),

# ── 25 BAND EXERCISES ─────────────────────────────────────────────────────────
dict(id="kids-ex-0143",slug="band-pull-apart",name="Band Pull-Apart",
    desc="A bilateral rear delt and upper back exercise where a resistance band is pulled apart horizontally — one of the most important shoulder health drills for posture, scapular stability, and overhead athlete injury prevention.",
    focus="Strength",pm=["shoulders","back"],sm=["biceps","core"],st=[],
    sub=["posterior deltoid","rhomboids","lower trapezius"],
    mp="pull_horizontal",fam="band-shoulder",dr=1,eq=["bands"],
    roles=["warmup","main"],goals=["build_shoulders","improve_posture","injury_prevention"],
    tags=["strength","bands","shoulder_health","posture","warmup","no_anchor"],
    form=["Hold the band at shoulder width with both hands, arms straight out in front.",
          "Pull the band apart horizontally, arms travelling out to the sides.",
          "Squeeze shoulder blades together at full range.",
          "Slowly return to start."],
    tips=["Thumbs up position (band at shoulder height) targets rear delt. Thumbs down targets lower trap."],
    mistakes=["Shrugging as you pull — keep shoulders depressed."],
    ts=["baseball","tennis","boxing","golf","swimming"],mt="warmup",diff="beginner",struct="warmup",
    met=3.0,pres={"sets":3,"reps":15,"rest_seconds":30,"tempo":"controlled"},rs=2.5),

dict(id="kids-ex-0144",slug="band-face-pull",name="Band Face Pull",
    desc="A band exercise anchored at face height — pulling the band toward the face with elbows high and wide — building posterior deltoid, external rotator, and upper trapezius strength critical for all throwing and serving athletes.",
    focus="Strength",pm=["shoulders","back"],sm=["biceps","core"],st=[],
    sub=["posterior deltoid","external rotators","middle trapezius"],
    mp="pull_horizontal",fam="band-shoulder",dr=1,eq=["bands"],
    roles=["warmup","main"],goals=["build_shoulders","improve_posture","injury_prevention"],
    tags=["strength","bands","shoulder_health","rear_delt","external_rotation"],
    form=["Anchor band at face height. Hold an end in each hand with palms facing in.",
          "Step back until there is tension in the band.",
          "Pull the band toward your face, elbows travelling high and wide.",
          "Externally rotate so thumbs point behind you at the end position."],
    tips=["Elbows should be above the band, not in line — this activates the external rotators."],
    mistakes=["Pulling to the neck instead of the face — target the space between eyes and chin."],
    ts=["baseball","tennis","boxing","swimming","golf"],mt="warmup",diff="beginner",struct="warmup",
    met=3.0,pres={"sets":3,"reps":15,"rest_seconds":30,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0145",slug="band-squat",name="Band Squat",
    desc="A squat with a resistance band looped above the knees — the band's pull trains the glutes to push the knees out, reinforcing proper knee tracking in young athletes learning squat mechanics.",
    focus="Strength",pm=["quads","glutes"],sm=["hamstrings","core","adductors"],st=["calves"],
    sub=["gluteus medius","vastus lateralis","gluteus maximus"],
    mp="squat",fam="band-lower-body",dr=1,eq=["bands"],
    roles=["warmup","main"],goals=["build_legs","improve_movement_quality","injury_prevention"],
    tags=["strength","bands","squat","knee_tracking","glute_activation"],
    form=["Place a loop band just above the knees. Stand hip-width apart.",
          "Squat down, pushing the knees out against the band resistance throughout.",
          "Lower to parallel or below, then drive up.",
          "The band wants to pull knees in — resist it the whole movement."],
    tips=["Feel the glutes working to push the knees out against the band pull."],
    mistakes=["Letting the knees collapse inward — the band is telling you when you're failing."],
    ts=["basketball","soccer","football","running"],mt="strength",diff="beginner",struct="main",
    met=5.0,pres={"sets":3,"reps":12,"rest_seconds":45,"tempo":"controlled"},rs=3.5),

dict(id="kids-ex-0146",slug="band-lateral-walk",name="Band Lateral Walk",
    desc="A lateral stepping exercise with a resistance band above the knees — activating gluteus medius and hip abductors against band resistance as athletes step sideways in an athletic stance.",
    focus="Strength",pm=["glutes"],sm=["quads","core"],st=["calves","ankles"],
    sub=["gluteus medius","tensor fasciae latae","hip abductors"],
    mp="locomotion",fam="band-lower-body",dr=1,eq=["bands"],
    roles=["warmup","main"],goals=["build_glutes","improve_hip_stability","injury_prevention"],
    tags=["strength","bands","glute_activation","hip_stability","warmup","lateral"],
    form=["Place a loop band above the knees. Stand in an athletic squat position.",
          "Step your right foot out to the right — shoulder width apart.",
          "Step the left foot in to return to hip width.",
          "Take 12 steps right, then 12 steps left, always maintaining the squat depth."],
    tips=["Stay low throughout — this keeps tension on the glute medius the whole set."],
    mistakes=["Standing up between steps — the bent-knee position is what loads the glutes."],
    ts=["basketball","soccer","football","tennis","running"],mt="warmup",diff="beginner",struct="warmup",
    met=3.5,pres={"sets":3,"reps":12,"rest_seconds":30,"tempo":"controlled"},rs=1.5),

dict(id="kids-ex-0147",slug="band-clamshell",name="Band Clamshell",
    desc="A side-lying hip external rotation exercise with a loop band — the primary drill for gluteus medius isolation, critical for knee health, hip stability, and preventing ACL injury in young athletes.",
    focus="Strength",pm=["glutes"],sm=["core"],st=[],
    sub=["gluteus medius","piriformis","hip external rotators"],
    mp="isolation",fam="glute-activation",dr=1,eq=["bands"],
    ps=True,roles=["warmup","main"],goals=["build_glutes","injury_prevention","improve_posture"],
    tags=["strength","bands","glute_med","hip_stability","warmup","acl_prevention"],
    form=["Lie on your right side with a loop band above the knees. Knees bent at 90 degrees, hips stacked.",
          "Keeping feet together, lift your top knee as high as you can without rotating the pelvis.",
          "Hold 1 second at the top. Lower slowly.",
          "Complete all reps, then switch sides."],
    tips=["Keep your pelvis stacked — don't let the top hip roll back."],
    mistakes=["Rolling the pelvis backward to get more range — keep it stacked."],
    ts=["running","soccer","basketball","football","tennis"],mt="warmup",diff="beginner",struct="warmup",
    met=2.5,pres={"sets":3,"reps":15,"rest_seconds":30,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0148",slug="band-good-morning",name="Band Good Morning",
    desc="A hip hinge drill with a resistance band looped around the shoulders and under the feet — the band adds a constant pull that reinforces the hip hinge pattern and activates the hamstrings and glutes for sprint preparation.",
    focus="Strength",pm=["hamstrings","glutes"],sm=["back","core"],st=["calves"],
    sub=["biceps femoris","gluteus maximus","erector spinae"],
    mp="hip_extension",fam="hip-hinge",dr=2,eq=["bands"],
    roles=["warmup","main"],goals=["build_legs","improve_hip_hinge","improve_performance"],
    tags=["strength","bands","hip_hinge","posterior_chain","warmup"],
    form=["Loop a band under both feet and bring it over your shoulders (or hold it at the hips).",
          "Stand with feet hip-width, slight knee bend.",
          "Hinge at the hips, pushing them back — feel the hamstring stretch as the band pulls.",
          "Drive hips forward to stand."],
    tips=["The band creates resistance in the most important part of the movement — the hinge."],
    mistakes=["Rounding the lower back — keep a neutral spine."],
    ts=["running","soccer","football","basketball"],mt="warmup",diff="beginner",struct="warmup",
    met=4.0,pres={"sets":3,"reps":12,"rest_seconds":30,"tempo":"controlled"},rs=3.5),

dict(id="kids-ex-0149",slug="band-chest-press-anchored",name="Band Chest Press (Anchored)",
    desc="A horizontal push against a band anchored behind the athlete — pressing forward from chest height to full extension, building pectoral, anterior deltoid, and tricep strength with accommodating resistance.",
    focus="Strength",pm=["chest"],sm=["triceps","shoulders","core"],st=[],
    sub=["pectoralis major","anterior deltoid","triceps brachii"],
    mp="push_horizontal",fam="band-push",dr=2,eq=["bands"],
    roles=["main"],goals=["build_chest","build_upper_body","improve_performance"],
    tags=["strength","bands","chest","pressing","upper_body"],
    form=["Anchor the band at chest height behind you. Hold an end in each hand at chest.",
          "Step forward until there is good tension.",
          "Press both hands forward to full arm extension.",
          "Slowly return to chest — the band pulls you back, so control it."],
    tips=["Stand in a slight lunge for stability — you will feel the pull trying to shift you."],
    mistakes=["Flaring elbows out to 90 degrees — keep them at 45 degrees."],
    ts=["boxing","basketball","baseball","football"],mt="strength",diff="beginner",struct="main",
    met=4.0,pres={"sets":3,"reps":12,"rest_seconds":45,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0150",slug="band-external-rotation",name="Band External Rotation",
    desc="An elbow-pinned shoulder external rotation drill with a band — directly targeting the infraspinatus and teres minor, the primary rotator cuff muscles that decelerate the arm and protect the shoulder in all throwing and hitting sports.",
    focus="Strength",pm=["shoulders"],sm=["back"],st=[],
    sub=["infraspinatus","teres minor","posterior capsule"],
    mp="isolation",fam="rotator-cuff",dr=1,eq=["bands"],
    ps=True,roles=["warmup","main"],goals=["injury_prevention","improve_posture","build_shoulders"],
    tags=["strength","bands","rotator_cuff","shoulder_health","warmup","overhead_sports"],
    form=["Anchor band at elbow height. Hold the far end with your right hand, elbow at 90 degrees.",
          "Pin your right elbow to your side — it must not move.",
          "Rotate your forearm outward (away from the band) against the resistance.",
          "Slowly return. Complete all reps then switch sides."],
    tips=["The elbow must stay pinned — movement only occurs at the shoulder joint."],
    mistakes=["Letting the elbow drift away from the body."],
    ts=["baseball","tennis","boxing","swimming","golf"],mt="warmup",diff="beginner",struct="warmup",
    met=2.5,pres={"sets":3,"reps":15,"rest_seconds":30,"tempo":"slow"},rs=3.0),

dict(id="kids-ex-0151",slug="band-internal-rotation",name="Band Internal Rotation",
    desc="The counterpart to external rotation — rotating the forearm inward against band resistance to strengthen the subscapularis and internal rotators, balancing shoulder health for young overhead athletes.",
    focus="Strength",pm=["shoulders"],sm=["chest","core"],st=[],
    sub=["subscapularis","pectoralis minor","teres major"],
    mp="isolation",fam="rotator-cuff",dr=1,eq=["bands"],
    ps=True,roles=["warmup","main"],goals=["injury_prevention","build_shoulders"],
    tags=["strength","bands","rotator_cuff","shoulder_health","warmup","internal_rotation"],
    form=["Anchor band at elbow height. Hold with right hand on the same side as the anchor, elbow at 90 degrees.",
          "Pin elbow to your side.",
          "Rotate forearm inward (across the body) against the band resistance.",
          "Slowly return. Switch sides after all reps."],
    tips=["Pair with external rotation in the same session for balanced shoulder health."],
    mistakes=["Using the wrist instead of the shoulder joint for the rotation."],
    ts=["baseball","tennis","boxing","swimming"],mt="warmup",diff="beginner",struct="warmup",
    met=2.5,pres={"sets":3,"reps":15,"rest_seconds":30,"tempo":"slow"},rs=3.0),

dict(id="kids-ex-0152",slug="band-hip-thrust",name="Band Hip Thrust",
    desc="A glute-dominant hip thrust with a resistance band looped across the hips — the band provides accommodating resistance (harder at the top), making the glutes work hardest where they are strongest.",
    focus="Strength",pm=["glutes"],sm=["hamstrings","core"],st=["back"],
    sub=["gluteus maximus","hamstring proximal","erector spinae"],
    mp="hip_extension",fam="glute-bridges",dr=1,eq=["bands"],
    roles=["warmup","main"],goals=["build_glutes","improve_performance","injury_prevention"],
    tags=["strength","bands","glutes","hip_extension","posterior_chain"],
    form=["Sit with upper back against a bench. Loop a band across your hips, secured to the floor or a heavy object.",
          "Plant feet hip-width, knees bent.",
          "Drive hips up, resisting the band pulling them back down.",
          "Squeeze glutes at the top. Lower controlled."],
    tips=["The band provides more resistance at full extension — squeeze extra hard at the top."],
    mistakes=["Hyperextending the lower back — stop at a flat bridge position."],
    ts=["running","soccer","football","basketball","tennis"],mt="strength",diff="beginner",struct="main",
    met=4.0,pres={"sets":3,"reps":15,"rest_seconds":45,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0153",slug="band-pull-down",name="Band Pull-Down",
    desc="A vertical pulling drill with a band anchored overhead — mimicking the lat pull-down machine to build latissimus dorsi and bicep strength for overhead athletic movements, without gym equipment.",
    focus="Strength",pm=["back"],sm=["biceps","core"],st=["shoulders"],
    sub=["latissimus dorsi","teres major","biceps brachii"],
    mp="pull_vertical",fam="band-back",dr=2,eq=["bands"],
    roles=["main"],goals=["build_back","improve_posture","improve_performance"],
    tags=["strength","bands","lats","back","pulling","overhead"],
    form=["Anchor a band overhead (top of a door, tree branch, or high anchor point).",
          "Grasp the band with both hands at arm's length above you, slight knee bend.",
          "Pull the band down toward your chest, driving elbows down and back.",
          "Slowly return to arm's length overhead."],
    tips=["Initiate by depressing the shoulder blades before you bend the elbows."],
    mistakes=["Pulling with the biceps only — engage the lats first."],
    ts=["baseball","tennis","basketball","swimming"],mt="strength",diff="beginner",struct="main",
    met=4.0,pres={"sets":3,"reps":12,"rest_seconds":45,"tempo":"controlled"},rs=3.5),

dict(id="kids-ex-0154",slug="band-monster-walk",name="Band Monster Walk",
    desc="A diagonal forward-stepping drill with a band at the ankles or knees — athletes walk in an X pattern against band resistance, building hip abductor endurance and knee stability for multidirectional sport movement.",
    focus="Strength",pm=["glutes"],sm=["quads","core"],st=["calves","ankles"],
    sub=["gluteus medius","gluteus minimus","hip abductors"],
    mp="locomotion",fam="band-lower-body",dr=2,eq=["bands"],
    roles=["warmup","main"],goals=["build_glutes","injury_prevention","improve_agility"],
    tags=["strength","bands","glutes","hip_abductors","agility","lateral"],
    form=["Place a loop band around your ankles. Stand with feet hip-width.",
          "Step your right foot diagonally forward-right while left stays back.",
          "Then step left foot forward-left.",
          "Walk forward in this monster X-pattern for 10 m, then reverse direction back."],
    tips=["Keep tension in the band at all times — never let feet get closer than hip-width."],
    mistakes=["Letting feet come together — maintain band tension throughout."],
    ts=["basketball","soccer","football","tennis","running"],mt="warmup",diff="beginner",struct="warmup",
    met=4.0,pres={"sets":3,"duration_seconds":30,"rest_seconds":30,"tempo":"controlled"},rs=1.5),

dict(id="kids-ex-0155",slug="band-row-mid-anchor",name="Band Mid Row",
    desc="A horizontal band row with the band anchored at mid-torso height — pulling the band to the lower ribs to build upper back, rhomboid, and posterior deltoid strength for improved posture and throwing mechanics.",
    focus="Strength",pm=["back"],sm=["biceps","rear_delts","core"],st=[],
    sub=["rhomboids","middle trapezius","posterior deltoid"],
    mp="pull_horizontal",fam="band-back",dr=1,eq=["bands"],
    roles=["warmup","main"],goals=["build_back","improve_posture","improve_performance"],
    tags=["strength","bands","back","rows","posture","pulling"],
    form=["Anchor band at mid-torso height. Hold an end in each hand, arms straight.",
          "Step back to create tension. Stand upright, core braced.",
          "Row both handles toward your lower ribs, squeezing the shoulder blades.",
          "Slowly return to arm extension."],
    tips=["Retract shoulder blades before you pull — lead with the back, not biceps."],
    mistakes=["Shrugging the traps — keep shoulders depressed throughout."],
    ts=["baseball","tennis","boxing","golf","basketball"],mt="warmup",diff="beginner",struct="warmup",
    met=3.5,pres={"sets":3,"reps":15,"rest_seconds":30,"tempo":"controlled"},rs=2.5),

dict(id="kids-ex-0156",slug="band-rotational-row",name="Band Rotational Row",
    desc="A single-arm band row with a thoracic rotation — pulling the band and rotating the torso to combine horizontal pulling with transverse-plane core power, directly replicating the mechanics of a baseball throw or tennis backhand.",
    focus="Strength",pm=["back","core"],sm=["shoulders","biceps"],st=["quads","glutes"],
    sub=["latissimus dorsi","obliques","posterior deltoid"],
    mp="rotation",fam="rotational-core",dr=3,eq=["bands"],
    ps=True,roles=["main"],goals=["build_back","build_core","improve_performance","improve_rotation"],
    tags=["strength","bands","rotational","sport_specific","throwing_pattern"],
    form=["Anchor band at shoulder height to your left. Stand sideways to the anchor.",
          "Hold the band with your right hand at full arm extension across your body.",
          "Row the band while simultaneously rotating your torso to the right.",
          "Return with control, loading back into the rotation. Switch sides after all reps."],
    tips=["Think: 'pull and rotate simultaneously' — not sequentially."],
    mistakes=["Rowing first then rotating — the power should come from combined movement."],
    ts=["baseball","tennis","golf","boxing"],mt="strength",diff="intermediate",struct="main",
    met=4.5,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=3.5),

dict(id="kids-ex-0157",slug="band-standing-hip-abduction",name="Band Standing Hip Abduction",
    desc="A single-leg standing hip abduction drill against band resistance — directly targeting gluteus medius, the critical hip stabiliser for injury prevention and lateral movement speed in field and court sports.",
    focus="Strength",pm=["glutes"],sm=["core","quads"],st=["calves","ankles"],
    sub=["gluteus medius","gluteus minimus","tensor fasciae latae"],
    mp="isolation",fam="glute-activation",dr=1,eq=["bands"],
    ps=True,uni=True,roles=["warmup","main"],goals=["build_glutes","injury_prevention","improve_balance"],
    tags=["strength","bands","glute_med","hip_abduction","lateral_stability","unilateral"],
    form=["Loop a band around your ankles. Stand on your right foot, left foot slightly raised.",
          "Keep the right knee slightly bent for stability.",
          "Lift the left leg out to the side against the band resistance — 30–45 degrees.",
          "Lower slowly. Complete all reps, then switch."],
    tips=["Keep the torso still — don't lean away from the working leg."],
    mistakes=["Leaning sideways to get more range — stay upright."],
    ts=["soccer","basketball","football","running","tennis"],mt="warmup",diff="beginner",struct="warmup",
    met=3.0,pres={"sets":3,"reps":15,"rest_seconds":30,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0158",slug="band-diagonal-chop",name="Band Diagonal Chop",
    desc="A high-to-low diagonal chopping movement against a band anchored high — training rotational core power through the full transverse and sagittal plane, essential for golf, tennis, and baseball hitting mechanics.",
    focus="Strength",pm=["core"],sm=["shoulders","glutes","back"],st=["quads"],
    sub=["obliques","transversus abdominis","anterior deltoid"],
    mp="rotation",fam="rotational-core",dr=2,eq=["bands"],
    ps=True,roles=["main"],goals=["build_core","improve_rotation","improve_performance"],
    tags=["strength","bands","rotational","core","sport_specific","chopping"],
    form=["Anchor a band high to your right side. Hold with both hands, arms extended right and high.",
          "Chop diagonally down-left, rotating your torso and allowing your right heel to pivot.",
          "Follow through until hands are at left hip height.",
          "Return slowly and repeat. Switch anchor side after all reps."],
    tips=["Exhale forcefully as you chop — it helps generate core power."],
    mistakes=["Moving with arms only — the power comes from hip rotation, not arm swinging."],
    ts=["golf","tennis","baseball","boxing"],mt="strength",diff="intermediate",struct="main",
    met=5.0,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0159",slug="band-single-leg-hip-thrust",name="Band Single-Leg Hip Thrust",
    desc="A unilateral hip thrust with a band across the hips — maximising glute demand by removing one leg from the equation and adding accommodating band resistance, building single-leg posterior chain strength for sprinting and cutting.",
    focus="Strength",pm=["glutes"],sm=["hamstrings","core"],st=["back"],
    sub=["gluteus maximus","hamstring proximal"],
    mp="hip_extension",fam="glute-bridges",dr=3,eq=["bands"],
    ps=True,uni=True,roles=["main"],goals=["build_glutes","improve_balance","improve_performance"],
    tags=["strength","bands","glutes","unilateral","hip_extension","advanced_beginner"],
    form=["Sit with upper back on a bench. Loop band across hips. Extend your right leg straight.",
          "Plant only your left foot on the floor.",
          "Drive through the left heel to thrust hips to ceiling.",
          "Lower with control. Complete all reps, then switch legs."],
    tips=["Initiate by pushing through the heel, not by arching the back."],
    mistakes=["Allowing the hip of the non-working leg to drop."],
    ts=["running","soccer","football","basketball"],mt="strength",diff="intermediate",struct="main",
    met=4.5,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0160",slug="band-pallof-press",name="Band Pallof Press",
    desc="A core anti-rotation stability exercise — band anchored laterally, pressing straight out from the chest and resisting the rotational pull — one of the most effective core stability exercises for rotational sport athletes.",
    focus="Strength",pm=["core"],sm=["shoulders","back","quads"],st=["glutes"],
    sub=["obliques","transversus abdominis","anterior deltoid"],
    mp="anti_extension",fam="anti-rotation-core",dr=2,eq=["bands"],
    ps=True,roles=["main"],goals=["build_core","injury_prevention","improve_performance"],
    tags=["strength","bands","anti_rotation","core","sport_specific","stability"],
    form=["Anchor band at chest height to your right. Stand sideways, holding band at chest.",
          "Brace your core tightly.",
          "Press the band straight out in front of your chest to arm's length.",
          "Hold 2 seconds, then pull back to chest. Repeat. Switch sides after all reps."],
    tips=["The wider your stance, the more stable — start wide and progress to narrow."],
    mistakes=["Letting the torso rotate toward the anchor when pressing out."],
    ts=["golf","tennis","baseball","boxing","soccer"],mt="strength",diff="beginner",struct="main",
    met=3.0,pres={"sets":3,"reps":12,"rest_seconds":45,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0161",slug="band-overhead-squat",name="Band Overhead Squat",
    desc="A squat with arms extended overhead holding a resistance band taut — the band provides tension that teaches lat and shoulder engagement in the overhead position while developing the mobility needed for overhead squats.",
    focus="Strength",pm=["quads","glutes","shoulders"],sm=["back","core","hamstrings"],st=["calves"],
    sub=["latissimus dorsi","vastus lateralis","gluteus maximus"],
    mp="squat",fam="squat-variations",dr=3,eq=["bands"],
    roles=["main"],goals=["build_legs","improve_mobility","improve_performance"],
    tags=["strength","bands","overhead_squat","mobility","compound","thoracic"],
    form=["Hold a band with both hands, arms extended wide overhead.",
          "Pull the band apart slightly to create tension — this engages the lats.",
          "Squat to parallel while keeping arms overhead and chest tall.",
          "Return to standing without lowering the arms."],
    tips=["If the arms fall forward, your thoracic mobility needs work — use a wider grip initially."],
    mistakes=["Arms drifting forward — the overhead position must be maintained."],
    ts=["basketball","soccer","tennis","baseball"],mt="strength",diff="intermediate",struct="main",
    met=5.0,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"slow"},rs=5.0),

dict(id="kids-ex-0162",slug="band-reverse-fly",name="Band Reverse Fly",
    desc="A band exercise with arms crossing in front then flying open wide to the sides — isolating the posterior deltoid and upper back, key for posture and shoulder-girdle balance in throwing and hitting athletes.",
    focus="Strength",pm=["shoulders","back"],sm=["biceps"],st=["core"],
    sub=["posterior deltoid","rhomboids","infraspinatus"],
    mp="pull_horizontal",fam="rear-delt-exercises",dr=1,eq=["bands"],
    roles=["warmup","main"],goals=["build_shoulders","improve_posture","injury_prevention"],
    tags=["strength","bands","rear_delt","posture","shoulder_health"],
    form=["Hold both ends of a band crossed at chest height (X in front).",
          "Pull the band open, spreading arms wide to the sides at shoulder height.",
          "Squeeze rear delts and shoulder blades at the end.",
          "Slowly return to the crossed starting position."],
    tips=["Keep a slight bend in the elbows — not straight, not too bent."],
    mistakes=["Letting the arms drop below shoulder height during the fly."],
    ts=["baseball","tennis","boxing","swimming","golf"],mt="warmup",diff="beginner",struct="warmup",
    met=3.0,pres={"sets":3,"reps":15,"rest_seconds":30,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0163",slug="band-hip-circle",name="Band Hip Circle",
    desc="A standing hip circle movement with a loop band around the knees — rotating the hip in all directions against band resistance to warm up the entire hip joint capsule and improve dynamic hip mobility.",
    focus="Flexibility",pm=["glutes","hip_flexors"],sm=["core","adductors"],st=["calves"],
    sub=["hip external rotators","hip flexors","gluteus medius"],
    mp="mobility",fam="hip-mobility",dr=1,eq=["bands"],
    roles=["warmup"],goals=["improve_mobility","improve_hip_stability","warmup"],
    tags=["warmup","bands","hip_mobility","joint_prep","dynamic"],
    form=["Place a loop band above your knees. Stand on your right foot, left foot lifted.",
          "Rotate the left hip in a full circle — forward, out, back, in.",
          "Make the circle as large as comfortable.",
          "8 circles forward, 8 backward on each leg."],
    tips=["The band adds awareness to the lateral part of the circle — feel it resist outward motion."],
    mistakes=["Making tiny circles — try to achieve full hip circumduction."],
    ts=["soccer","golf","basketball","running"],mt="warmup",diff="beginner",struct="warmup",
    met=2.5,pres={"sets":2,"reps":8,"rest_seconds":15,"tempo":"slow"},
    ps=True,pr="mobility"),

dict(id="kids-ex-0164",slug="band-deadlift",name="Band Deadlift",
    desc="A hip hinge deadlift using a resistance band under the feet and held in both hands — building the full posterior chain (glutes, hamstrings, lower back) with accommodating resistance ideal for teaching deadlift form without heavy loads.",
    focus="Strength",pm=["glutes","hamstrings"],sm=["back","core","quads"],st=["calves"],
    sub=["gluteus maximus","biceps femoris","erector spinae"],
    mp="hip_extension",fam="hip-hinge",dr=2,eq=["bands"],
    roles=["main"],goals=["build_legs","build_back","improve_performance"],
    tags=["strength","bands","deadlift","posterior_chain","compound"],
    form=["Stand on the middle of the band, feet hip-width. Hold both ends.",
          "Hinge at the hips, maintaining a flat back, until hands are at mid-shin level.",
          "Drive hips forward and squeeze glutes to return to standing.",
          "The band provides increasing resistance as you stand — most resistance at lockout."],
    tips=["Think 'push the floor away' rather than 'pull the band up' — leg drive first."],
    mistakes=["Rounding the lower back — chest up, hinge from the hips."],
    ts=["running","soccer","football","basketball","baseball"],mt="strength",diff="beginner",struct="main",
    met=5.0,pres={"sets":3,"reps":12,"rest_seconds":60,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0165",slug="band-tricep-pushdown",name="Band Tricep Pushdown",
    desc="An elbow extension exercise with the band anchored overhead — pushing the band down to full elbow extension to isolate the tricep, building pushing endurance for throwing follow-through and punch extension.",
    focus="Strength",pm=["triceps"],sm=["shoulders","core"],st=[],
    sub=["triceps brachii lateral head","medial head"],
    mp="isolation",fam="tricep-exercises",dr=1,eq=["bands"],
    roles=["main"],goals=["build_arms","improve_performance"],
    tags=["strength","bands","triceps","isolation","elbow_extension"],
    form=["Anchor band overhead. Hold with both hands (or one) at chest level.",
          "Pin elbows to your sides — they must not move.",
          "Push the band down to full arm extension, squeezing the tricep.",
          "Slowly let the band return up, resisting the pull."],
    tips=["Elbows must stay at your sides — they are the pivot point."],
    mistakes=["Flaring elbows out or letting them drift forward."],
    ts=["baseball","tennis","boxing"],mt="strength",diff="beginner",struct="main",
    met=3.5,pres={"sets":3,"reps":15,"rest_seconds":45,"tempo":"controlled"},rs=2.5),

dict(id="kids-ex-0166",slug="band-bicep-curl",name="Band Bicep Curl",
    desc="A standing bicep curl with a band under the feet — accommodating resistance provides consistent tension throughout the curl arc, making it an effective beginner tool for building elbow flexor strength without dumbbells.",
    focus="Strength",pm=["biceps"],sm=["forearms","shoulders"],st=["core"],
    sub=["biceps brachii","brachialis","brachioradialis"],
    mp="isolation",fam="bicep-curl-variations",dr=1,eq=["bands"],
    roles=["main"],goals=["build_arms","improve_performance"],
    tags=["strength","bands","biceps","isolation","beginner_friendly"],
    form=["Stand on the band, feet hip-width. Hold an end in each hand, palms up.",
          "Curl both hands up toward your shoulders.",
          "Squeeze at the top. Lower slowly — the band keeps tension all the way down."],
    tips=["Unlike dumbbells, bands have most resistance at the top — don't rush it down."],
    mistakes=["Swinging the torso — keep the upper arms pinned to your sides."],
    ts=["baseball","boxing","tennis"],mt="strength",diff="beginner",struct="main",
    met=3.5,pres={"sets":3,"reps":15,"rest_seconds":45,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0167",slug="band-woodchop-low-to-high",name="Band Wood Chop Low to High",
    desc="A low-to-high rotational band exercise — chopping from hip level diagonally to overhead — training the reverse golf swing and tennis topspin load pattern, engaging the core in the upward power phase.",
    focus="Strength",pm=["core","shoulders"],sm=["glutes","back","quads"],st=[],
    sub=["obliques","anterior deltoid","transversus abdominis"],
    mp="rotation",fam="rotational-core",dr=2,eq=["bands"],
    ps=True,roles=["main"],goals=["build_core","improve_rotation","improve_performance"],
    tags=["strength","bands","rotational","sport_specific","low_to_high","core"],
    form=["Anchor band low to your right. Hold with both hands at right hip level.",
          "Rotate up and left, lifting the band diagonally overhead to the left.",
          "Allow the right heel to pivot. Look at your hands as they rise.",
          "Lower slowly and repeat. Switch sides after all reps."],
    tips=["Drive from the hips and core — the arms just guide the band."],
    mistakes=["Lifting only with the arms — initiate from the ground up."],
    ts=["golf","tennis","baseball","boxing"],mt="strength",diff="intermediate",struct="main",
    met=5.0,pres={"sets":3,"reps":10,"rest_seconds":60,"tempo":"controlled"},rs=3.0),
]

def main():
    with open(SRC) as f:
        data=json.load(f)
    before=len(data)
    new_exs=[ex(d) for d in DEFS]
    data.extend(new_exs)
    with open(SRC,'w') as f:
        json.dump(data,f,indent=2)
    print(f"Batch 2 done: {len(new_exs)} entries added, running total {len(data)}/500 (was {before})")

if __name__=='__main__':
    main()
