#!/usr/bin/env python3
"""Batch 1: 67 entries — Kids-focused warmup/cardio."""
import json, os
SRC = os.path.join(os.path.dirname(__file__), '..', 'data', 'exercises.json')
SN = ("MET values estimated from Compendium of Physical Activities (Ainsworth 2011) "
      "and ACSM/NSCA Youth Exercise Guidelines; weight assumed 30 kg (Kids 6-9), 40 kg (Kids+Tweens), 47 kg (Tweens+Teens).")
def ex(d):
    wt=d.get('wt',35); met=d.get('met',4.0); dur=d.get('dur',0.8)
    cpm=round(met*wt/60,1); ce=round(cpm*dur,1)
    role=d.get('pr','cardio'); pres=d.get('pres',{'sets':2,'duration_seconds':20,'rest_seconds':20})
    return {
        "id":d['id'],"slug":d['slug'],"name":d['name'],"description":d['desc'],
        "level":d.get('level','Beginner'),"primary_focus":d.get('focus','Coordination'),
        "body_area":None,"equipment":d.get('eq',['bodyweight']),
        "primary_muscles":d.get('pm',[]),"secondary_muscles":d.get('sm',[]),
        "stabilizer_muscles":d.get('st',[]),"muscles_subregions":d.get('sub',[]),
        "movement_pattern":d['mp'],"family":d.get('fam',d['slug']),
        "difficulty_rank":d.get('dr',1),"workout_roles":d.get('roles',['warmup','main']),
        "sports":d.get('sports',[]),"goals":d.get('goals',['improve_coordination','home_workout']),
        "settings":d.get('settings',['home','outdoor','gym','school']),
        "tags":d.get('tags',['low_impact','beginner_friendly','kids_friendly']),
        "contraindications":d.get('contra',[]),
        "narration_script":None,"popularity":None,"variant_of":None,
        "instructions":{"form":d.get('form',['Follow the movement as described.']),"proTips":d.get('tips',[]),"commonMistakes":d.get('mistakes',[])},
        "classification":{"family":d.get('fam',d['slug']),"isPerSide":d.get('ps',False),
            "unilateral":d.get('uni',False),"energySystem":d.get('es','glycolytic'),
            "kineticChain":d.get('kc','closed'),"planeOfMotion":d.get('plane',['sagittal']),
            "bodyweightOnly":d.get('eq',['bodyweight'])==['bodyweight'],
            "difficultyRank":d.get('dr',1),"movementPattern":d['mp'],
            "contractionTypes":d.get('ct',['concentric','eccentric']),
            "compoundOrIsolation":d.get('ci','compound')},
        "demands":{"cns":d.get('cns','low'),"noise":d.get('noise','moderate'),
            "space":d.get('space','medium'),"stability":d.get('stab','medium')},
        "prescription":{"isHold":d.get('hold',False),"default":{role:pres},"defaultHoldSeconds":d.get('hs',None)},
        "energy":{"metValue":met,"sourceNote":SN,"durationMinutes":dur,
            "caloriesEstimate":ce,"caloriesPerMinute":cpm,"assumedUserWeightKg":wt,"proteinPostWorkoutG":None},
        "timing":{"repSecondsEstimate":d.get('rs',None),"videoPortraitSeconds":None,"videoLandscapeSeconds":None},
        "media":{"image":{"path":None,"available":False},"videoPortrait":{"path":None,"available":False},"videoLandscape":{"path":None,"available":False}},
        "cv":None,"alternatives":[],"_raw":None,
        "taxonomy":{"age_bands_suggested":d['bands'],"age_bands_confirmed":None,
            "sports_suggested":d.get('ts',[]),"sports_confirmed":None,
            "position":[],"position_confirmed":None,
            "movement_type":d.get('mt','cardio'),"difficulty":d.get('diff','beginner'),
            "structure":d.get('struct','main'),"safety_flags":d.get('flags',[])},
        "review_status":"pending"}

K=["Kids"]; KT=["Kids","Tweens"]; TT=["Tweens","Teens"]

DEFS=[
# ── 35 KIDS-ONLY ──────────────────────────────────────────────────────────────
dict(id="kids-ex-0051",slug="cheetah-sprint-burst",name="Cheetah Sprint Burst",
    desc="Short explosive sprint bursts where children run as fast as a cheetah for 5 seconds then walk — building speed, leg power, and anaerobic capacity through playful interval running.",
    focus="Cardio",pm=["quads","glutes"],sm=["calves","hamstrings"],mp="locomotion",fam="sprint-games",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=8.0,dur=0.5,
    form=["Stand at a starting line and get ready like a cheetah crouching before a hunt.",
          "On 'GO!' sprint as fast as you can for 5 seconds — all out!",
          "Slow to a walk for 15 seconds, then sprint again."],
    tips=["Pump your arms hard — fast arms make fast legs."],
    mistakes=["Starting too fast before 'GO!' — wait for the signal."],
    roles=["main"],pres={"sets":4,"duration_seconds":5,"rest_seconds":15},
    tags=["kids_friendly","cardio","sprint","games_based","fun"]),

dict(id="kids-ex-0052",slug="crab-soccer",name="Crab Soccer",
    desc="A games-based movement activity where children play soccer from the crab-walk position — building upper body strength, core stability, and cardiovascular fitness simultaneously.",
    focus="Cardio",pm=["shoulders","core","glutes"],sm=["triceps","quads"],mp="locomotion",fam="animal-games",
    dr=2,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=5.5,dur=2.0,
    form=["Get into crab position: hands behind you, hips lifted, face up.",
          "Kick a soft ball to a partner or toward a goal using only your feet.",
          "Move around in crab position to chase the ball — keep hips up!"],
    tips=["Keep hips high — crab soccer is a core workout, not just a game."],
    mistakes=["Letting hips sag to the floor."],
    roles=["main"],pres={"sets":1,"duration_seconds":120,"rest_seconds":30},
    tags=["kids_friendly","games_based","cardio","upper_body","fun"],ts=["soccer"]),

dict(id="kids-ex-0053",slug="bear-crawl-relay",name="Bear Crawl Relay",
    desc="A relay-race game where children bear-crawl to a cone and back as fast as possible — combining locomotor strength, coordination, and competitive fun.",
    focus="Cardio",pm=["shoulders","core","quads"],sm=["chest","back"],mp="locomotion",fam="animal-games",
    dr=2,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=6.0,dur=1.0,
    form=["Start on hands and feet (hips up, knees off ground) at the start line.",
          "Bear-crawl forward to the cone (5–10 m), touch it, and crawl back.",
          "Tag the next person — fastest team wins!"],
    tips=["Keep your back flat — don't let hips sag or pike up too high."],
    mistakes=["Dropping to knees — stay on hands and feet the whole way."],
    roles=["main"],pres={"sets":3,"reps":1,"rest_seconds":30,"tempo":"fast"},
    tags=["kids_friendly","games_based","cardio","upper_body","relay"]),

dict(id="kids-ex-0054",slug="rabbit-ears-jump",name="Rabbit Ears Jump",
    desc="A fun bunny-themed jump where children place hands on head as 'ears' and do two-footed hops forward with ears on — practising jumping mechanics with a playful focus cue.",
    focus="Coordination",pm=["quads","calves","glutes"],sm=["core"],mp="plyometric",fam="jumping-games",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=5.0,dur=0.7,
    form=["Place both hands on top of your head — these are your big rabbit ears!",
          "Keeping ears on, bend your knees and hop forward with both feet.",
          "Land softly with bent knees and immediately hop again."],
    tips=["Keeping hands on head makes you use your legs more for momentum — embrace it!"],
    mistakes=["Removing hands to balance — challenge yourself to keep ears on."],
    roles=["warmup","main"],pres={"sets":3,"duration_seconds":20,"rest_seconds":20},
    tags=["kids_friendly","fun","plyometric","games_based","cardio"]),

dict(id="kids-ex-0055",slug="lion-pounce",name="Lion Pounce",
    desc="A crouched-start reaction jump where children wait in a low squat like a lion hiding in grass, then explode upward on a signal — training explosive power and reaction time.",
    focus="Power",pm=["quads","glutes","calves"],sm=["core"],mp="plyometric",fam="jumping-games",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=6.0,dur=0.5,
    form=["Crouch in a low squat position — you're a lion hiding in the grass.",
          "Wait for the signal (a clap or 'ROAR!').",
          "Explode upward as high as you can, roaring like a lion!",
          "Land softly and crouch back down to wait for the next pounce."],
    tips=["The longer you wait in the crouch, the more explosive your pounce will be."],
    mistakes=["Jumping before the signal — patience is part of the game."],
    roles=["warmup","main"],pres={"sets":4,"reps":5,"rest_seconds":15,"tempo":"explosive"},
    tags=["kids_friendly","games_based","plyometric","reaction","fun"]),

dict(id="kids-ex-0056",slug="monkey-jump-reach",name="Monkey Jump Reach",
    desc="Children jump from foot to foot while reaching upward with alternating arms as if swinging between imaginary vines — combining lateral locomotion, coordination, and upper body reach.",
    focus="Coordination",pm=["quads","calves","shoulders"],sm=["core","glutes"],mp="plyometric",fam="animal-games",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=5.5,dur=0.7,
    form=["Stand and imagine there are monkey bars above your head.",
          "Jump from your right foot to your left, reaching your right arm high as you jump.",
          "Land and jump back to the right, reaching the left arm high.",
          "Swing and jump like a monkey working along the bars!"],
    tips=["The reach upward helps drive the jump — think tall!"],
    mistakes=["Forgetting to reach — the arm reach is half the exercise."],
    roles=["warmup","main"],pres={"sets":2,"duration_seconds":25,"rest_seconds":20},
    tags=["kids_friendly","games_based","coordination","cardio","fun"]),

dict(id="kids-ex-0057",slug="playground-swing-arms",name="Playground Swing Arms",
    desc="An upper-body pendulum movement where children stand, grip imaginary bars and swing their arms in big forward pendulum arcs — warming up the shoulder joint and building rhythmic movement confidence.",
    focus="Flexibility",pm=["shoulders"],sm=["back","core"],mp="mobility",fam="shoulder-mobility",
    dr=1,bands=K,mt="warmup",diff="beginner",struct="warmup",wt=30,met=2.2,dur=0.5,
    form=["Stand with feet hip-width and raise both arms straight overhead.",
          "Swing both arms forward and down like a pendulum — big, smooth arcs.",
          "Let momentum carry them behind you, then swing forward again.",
          "Do 10 forward swings, then 10 backward."],
    tips=["Let the arms be loose and heavy — like ropes swinging."],
    mistakes=["Swinging with stiff arms — relax and let gravity help."],
    roles=["warmup"],pres={"sets":2,"reps":10,"rest_seconds":10,"tempo":"rhythmic"},
    tags=["kids_friendly","warmup","shoulder_mobility","fun"],pr="mobility"),

dict(id="kids-ex-0058",slug="merry-go-round-spin",name="Merry-Go-Round Spin",
    desc="A gentle spinning-in-place drill where children extend their arms and spin slowly on the spot — developing vestibular tolerance, spatial orientation, and body awareness.",
    focus="Coordination",pm=["core"],sm=["shoulders"],mp="mobility",fam="vestibular-games",
    dr=1,bands=K,mt="warmup",diff="beginner",struct="warmup",wt=30,met=2.0,dur=0.5,
    form=["Stand with feet together and arms extended wide like aeroplane wings.",
          "Slowly spin in one direction for 3 full rotations.",
          "Stop, find your balance, then spin the other way for 3 rotations.",
          "Start slow and only spin as fast as feels comfortable."],
    tips=["Focus on a point on the wall each time you face it to reduce dizziness."],
    mistakes=["Spinning too fast — slow and controlled is safer and more effective."],
    roles=["warmup"],pres={"sets":2,"reps":3,"rest_seconds":15,"tempo":"slow"},
    tags=["kids_friendly","vestibular","warmup","balance"],pr="mobility"),

dict(id="kids-ex-0059",slug="head-shoulders-knees-toes-drill",name="Head Shoulders Knees Toes Drill",
    desc="The classic children's song turned into a progressive movement drill — touching each body part faster each round, building flexibility, body awareness, and a joyful warm-up atmosphere.",
    focus="Flexibility",pm=["hamstrings","back"],sm=["core","shoulders"],mp="mobility",fam="song-movement",
    dr=1,bands=K,mt="warmup",diff="beginner",struct="warmup",wt=30,met=3.5,dur=1.0,
    form=["Stand with feet hip-width apart.",
          "Touch your head, then shoulders, then knees, then toes in sequence.",
          "Sing 'Head, shoulders, knees and toes' as you touch each part.",
          "Each round try to go a little faster without losing accuracy."],
    tips=["Bend at the hips (not the waist) when reaching for knees and toes."],
    mistakes=["Bending the knees excessively — try to keep them soft but not fully bent."],
    roles=["warmup"],pres={"sets":3,"reps":4,"rest_seconds":10,"tempo":"progressive"},
    tags=["kids_friendly","warmup","song_based","flexibility","body_awareness"],pr="mobility"),

dict(id="kids-ex-0060",slug="musical-spots-drill",name="Musical Spots Drill",
    desc="A musical-chairs-style movement drill where children jog around cones or spots and rush to stand on one when music stops — combining cardiovascular running with quick deceleration and reaction.",
    focus="Cardio",pm=["quads","glutes","calves"],sm=["core"],mp="locomotion",fam="games-based-movement",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=6.5,dur=2.0,
    form=["Set out cones or spots in a circle (one fewer than children).",
          "Jog around the circle while music plays.",
          "When music stops — race to stand on a spot!",
          "The child without a spot does 5 jumping jacks before next round."],
    tips=["Keep jogging at a steady pace — don't slow down waiting for music to stop."],
    mistakes=["Walking instead of jogging between stops."],
    roles=["main"],pres={"sets":1,"duration_seconds":120,"rest_seconds":30},
    tags=["kids_friendly","games_based","cardio","reaction","fun"]),

dict(id="kids-ex-0061",slug="traffic-lights-run",name="Traffic Lights Run",
    desc="A reaction and cardiovascular game where children run, slow, or freeze based on red/amber/green signals — practising deceleration control and building aerobic capacity through play.",
    focus="Cardio",pm=["quads","glutes","calves"],sm=["core","hamstrings"],mp="locomotion",fam="games-based-movement",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=6.0,dur=2.0,
    form=["Run freely in an open space.",
          "GREEN = run fast!",
          "AMBER = slow jog.",
          "RED = freeze completely still.",
          "The leader calls colours — react as fast as possible!"],
    tips=["The quicker you react to RED, the better your deceleration skills become."],
    mistakes=["Slowing down in anticipation before RED is called."],
    roles=["warmup","main"],pres={"sets":1,"duration_seconds":120,"rest_seconds":30},
    tags=["kids_friendly","games_based","cardio","reaction","fun"]),

dict(id="kids-ex-0062",slug="simon-says-jump-series",name="Simon Says Jump Series",
    desc="A classic Simon Says game focusing exclusively on jump and balance actions — squat jumps, star jumps, tuck jumps, and single-leg holds — combining cognitive engagement with explosive movement.",
    focus="Coordination",pm=["quads","glutes","calves"],sm=["core"],mp="plyometric",fam="games-based-movement",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=5.5,dur=1.5,
    form=["Leader calls 'Simon Says [jump action]' — only move if Simon Says!",
          "Actions: 'star jump', 'squat and hold', 'hop on right foot', 'balance on one leg'.",
          "Anyone who moves without 'Simon Says' does 5 extra hops as a fun penalty."],
    tips=["Listen carefully — the trick is cognitive, not physical!"],
    mistakes=["Moving too automatically — listen for 'Simon Says' first."],
    roles=["warmup","main"],pres={"sets":1,"duration_seconds":90,"rest_seconds":20},
    tags=["kids_friendly","games_based","cardio","cognitive","reaction","fun"]),

dict(id="kids-ex-0063",slug="tag-and-dodge-sprint",name="Tag and Dodge Sprint",
    desc="A classic tag game structured as a movement drill — one child is 'it' and chases others, who dodge and change direction — building agility, cardiovascular fitness, and spatial awareness.",
    focus="Cardio",pm=["quads","glutes","calves"],sm=["core","hamstrings"],mp="locomotion",fam="games-based-movement",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=7.5,dur=3.0,
    form=["Designate one child as 'it'.",
          "'It' chases the others who dodge, sidestep, and change direction to avoid being tagged.",
          "When tagged, swap roles.",
          "Play in a bounded area — stay within the lines!"],
    tips=["Change direction suddenly to dodge — don't just run in straight lines."],
    mistakes=["Running only in circles — mix directions to make the game harder."],
    roles=["main"],pres={"sets":1,"duration_seconds":180,"rest_seconds":30},
    tags=["kids_friendly","games_based","cardio","agility","social","fun"]),

dict(id="kids-ex-0064",slug="balloon-tap-challenge",name="Balloon Tap Challenge",
    desc="Children keep a balloon in the air using only specific body parts (head, elbow, knee) on command — building dynamic balance, reaction, and body part awareness in a joyful movement context.",
    focus="Coordination",pm=["shoulders","core","quads"],sm=["calves"],mp="locomotion",fam="games-based-movement",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=3.5,dur=1.5,
    form=["Inflate a balloon. Leader calls a body part: 'ELBOW!'",
          "Children must tap the balloon using only that body part to keep it off the floor.",
          "Next call: 'KNEE!' — swap to that part immediately.",
          "How long can you keep it up?"],
    tips=["Move your feet constantly to position yourself under the balloon."],
    mistakes=["Standing still and reaching — stay on the move."],
    roles=["warmup","main"],pres={"sets":2,"duration_seconds":60,"rest_seconds":20},
    tags=["kids_friendly","games_based","coordination","reaction","fun"],noise="loud"),

dict(id="kids-ex-0065",slug="leap-frog",name="Leap Frog",
    desc="A classic cooperative game where children crouch in a line and leap over each other — combining explosive squat jumps, coordination, and team play in a timeless movement activity.",
    focus="Power",pm=["quads","glutes","calves"],sm=["core","shoulders"],mp="plyometric",fam="cooperative-games",
    dr=2,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=5.5,dur=1.5,
    form=["One child crouches in a tight tuck position (the 'frog').",
          "The child behind places hands on the frog's back and leaps over, landing on both feet.",
          "The leaper then crouches and the next person leaps over them.",
          "Continue down the line, then walk back to the start."],
    tips=["Leapers: spread your legs wide to clear your partner safely."],
    mistakes=["Crouching too tall — stay low and tight so leapers can clear you."],
    roles=["main"],pres={"sets":3,"reps":5,"rest_seconds":30},
    tags=["kids_friendly","games_based","cooperative","plyometric","fun"]),

dict(id="kids-ex-0066",slug="wheelbarrow-walk",name="Wheelbarrow Walk",
    desc="A partner drill where one child walks on their hands while the other holds their legs — building upper body strength, core stability, and trust through cooperative movement.",
    focus="Strength",pm=["shoulders","chest","core"],sm=["triceps","back"],mp="locomotion",fam="cooperative-games",
    dr=2,bands=K,mt="strength",diff="beginner",struct="main",wt=30,met=5.0,dur=1.0,
    form=["Partner A places hands on floor, partner B holds their ankles, lifting their legs.",
          "Partner A walks on hands while B guides the legs.",
          "Walk 5–10 metres, then swap roles."],
    tips=["Wheelbarrow: keep core braced to stop hips sagging."],
    mistakes=["Bending elbows too much — press through straight arms."],
    roles=["main"],pres={"sets":2,"reps":2,"rest_seconds":40},
    tags=["kids_friendly","cooperative","upper_body","strength","fun"]),

dict(id="kids-ex-0067",slug="superhero-landing-pose",name="Superhero Landing Pose",
    desc="A jump-and-land drill where children jump and land in a confident superhero one-knee pose, building safe landing mechanics and a sense of confident physical expression.",
    focus="Power",pm=["quads","glutes"],sm=["core","calves"],mp="plyometric",fam="jumping-games",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=5.0,dur=0.6,
    form=["Jump from two feet, gaining as much height as possible.",
          "As you land, drop one knee toward the floor and press the opposite fist to the ground.",
          "Hold the heroic pose for 2 seconds — you just saved the day!",
          "Stand, reset, and jump again."],
    tips=["The landing knee should barely touch the floor — control the descent."],
    mistakes=["Crashing the knee down hard — land controlled and quiet."],
    roles=["main"],pres={"sets":3,"reps":6,"rest_seconds":20,"tempo":"controlled"},
    tags=["kids_friendly","games_based","plyometric","landing_mechanics","fun"]),

dict(id="kids-ex-0068",slug="spider-man-crawl-kids",name="Spider-Man Wall Crawl",
    desc="Children crawl in a lateral direction along a wall (or imaginary wall), keeping wide hands and feet like Spider-Man — building cross-body coordination and lateral strength.",
    focus="Coordination",pm=["shoulders","core","quads"],sm=["chest","back","glutes"],mp="locomotion",fam="animal-games",
    dr=2,bands=K,mt="strength",diff="beginner",struct="main",wt=30,met=4.5,dur=0.8,
    form=["Get into a push-up position facing a wall.",
          "Step your right hand and right foot out to the right simultaneously.",
          "Follow with left hand and left foot — lateral crawl like Spidey on the wall.",
          "Travel 3 metres right, then 3 metres back left."],
    tips=["Keep hips low — Spider-Man stays flat on the wall."],
    mistakes=["Moving same-side arm and leg together — cross-body pattern is key."],
    roles=["main"],pres={"sets":2,"duration_seconds":25,"rest_seconds":30},
    tags=["kids_friendly","games_based","coordination","upper_body","fun"]),

dict(id="kids-ex-0069",slug="rocket-launch-jump",name="Rocket Launch Jump",
    desc="A progressive crouch-to-jump sequence where children slowly lower into a deep squat counting down like a rocket launch, then explode upward at zero — building explosive leg power with a fun narrative.",
    focus="Power",pm=["quads","glutes","calves"],sm=["core"],mp="plyometric",fam="jumping-games",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=6.5,dur=0.5,
    form=["Stand with feet shoulder-width apart, arms by sides.",
          "Slowly lower into the deepest squat you can, counting down: 5-4-3-2-1...",
          "At ZERO — blast upward as high as possible, arms reaching for the sky!",
          "WHOOSH! Land softly, reset, and launch again."],
    tips=["The slower the countdown, the more power you build during the hold."],
    mistakes=["Rushing the countdown — the slow eccentric builds the launch energy."],
    roles=["warmup","main"],pres={"sets":4,"reps":5,"rest_seconds":20,"tempo":"explosive"},
    tags=["kids_friendly","games_based","plyometric","power","fun"]),

dict(id="kids-ex-0070",slug="rainbow-reach",name="Rainbow Reach",
    desc="A standing side-bend and overhead reach sequence where children trace a big rainbow arc from one side to the other — developing lateral trunk flexibility and shoulder mobility through imaginative movement.",
    focus="Flexibility",pm=["back","shoulders"],sm=["core","hamstrings"],mp="mobility",fam="flexibility-games",
    dr=1,bands=K,mt="warmup",diff="beginner",struct="warmup",wt=30,met=2.0,dur=0.5,
    form=["Stand with feet hip-width apart and arms at sides.",
          "Reach your right arm up and over your head in a big arc, bending to the left.",
          "Trace the rainbow all the way to the left side, then sweep back.",
          "Do 5 arcs to each side — make your rainbow as big as possible!"],
    tips=["Feel the stretch down the side of your body — that's the rainbow lengthening."],
    mistakes=["Collapsing forward — keep the movement in the side plane, not forward."],
    roles=["warmup"],pres={"sets":2,"reps":5,"rest_seconds":10,"tempo":"slow"},
    tags=["kids_friendly","warmup","flexibility","creativity","fun"],pr="mobility"),

dict(id="kids-ex-0071",slug="cloud-float-balance",name="Cloud Float Balance",
    desc="A slow-motion balance imagination game where children pretend to float on a cloud and hold gentle single-leg poses — building proprioception and concentration through calm, mindful movement.",
    focus="Balance",pm=["core","calves"],sm=["glutes","hip_abductors"],mp="hold",fam="balance-challenges",
    dr=1,bands=K,mt="warmup",diff="beginner",struct="warmup",wt=30,met=1.8,dur=0.5,
    hold=True,hs=15,
    form=["Close your eyes for a moment and imagine you're standing on a soft cloud.",
          "Slowly lift one foot a few centimetres off the ground and hold perfectly still.",
          "The cloud wobbles if you're not balanced — hold for 10 seconds.",
          "Switch feet and float on the other side."],
    tips=["Spread your toes wide like roots going into the cloud."],
    mistakes=["Tensing everything up — floating is calm and gentle."],
    roles=["warmup"],pres={"sets":3,"duration_seconds":10,"rest_seconds":10,"tempo":"static"},
    tags=["kids_friendly","balance","mindful","warmup","imagination"],pr="mobility"),

dict(id="kids-ex-0072",slug="worm-wiggle",name="Worm Wiggle",
    desc="A ground-based segmental spinal mobility drill where children lie on their back and wave their body like a worm — mobilising the spine segment by segment and building body awareness.",
    focus="Flexibility",pm=["back","core"],sm=["glutes","shoulders"],mp="mobility",fam="ground-movement",
    dr=1,bands=K,mt="warmup",diff="beginner",struct="warmup",wt=30,met=2.2,dur=0.5,
    form=["Lie on your back with arms by your sides.",
          "Start the wiggle from your feet — point and flex your feet rhythmically.",
          "Let the wiggle travel up through your ankles, knees, hips, back, shoulders, and neck.",
          "Wave like a worm — full body segmental motion!"],
    tips=["Move each segment in sequence — worms don't just wiggle everything at once."],
    mistakes=["Only moving the shoulders or hips — try to isolate each segment."],
    roles=["warmup"],pres={"sets":2,"duration_seconds":20,"rest_seconds":10,"tempo":"rhythmic"},
    tags=["kids_friendly","warmup","spinal_mobility","body_awareness","fun"],pr="mobility"),

dict(id="kids-ex-0073",slug="turtle-shell-hold",name="Turtle Shell Hold",
    desc="A bodyweight core hold where children curl into a tuck on their back, hold their knees, and rock gently like a turtle on its shell — building lumbar flexion endurance and massaging the lower back.",
    focus="Strength",pm=["core"],sm=["back","hip_flexors"],mp="hold",fam="core-games",
    dr=1,bands=K,mt="strength",diff="beginner",struct="main",wt=30,met=2.5,dur=0.5,
    hold=True,hs=20,
    form=["Lie on your back and pull both knees into your chest.",
          "Wrap your arms around your shins — you are a turtle in your shell!",
          "Hold for 20 seconds, rocking gently back and forth.",
          "Slowly release and stretch out flat."],
    tips=["The rock massages your spine — keep it gentle and rhythmic."],
    mistakes=["Forcing the chin down to chest — keep the neck relaxed."],
    roles=["main","cooldown"],pres={"sets":3,"duration_seconds":20,"rest_seconds":15,"tempo":"static"},
    tags=["kids_friendly","core","back_care","fun","calming"],pr="mobility"),

dict(id="kids-ex-0074",slug="butterfly-wings-stretch",name="Butterfly Wings Stretch",
    desc="A seated inner thigh and hip opener where children sit with feet together and gently flap their knees up and down like butterfly wings — improving hip external rotation and adductor flexibility.",
    focus="Flexibility",pm=["glutes"],sm=["adductors"],mp="mobility",fam="hip-mobility",
    dr=1,bands=K,mt="warmup",diff="beginner",struct="warmup",wt=30,met=1.8,dur=0.5,
    form=["Sit on the floor and press the soles of your feet together in front of you.",
          "Hold your ankles and let your knees fall out to the sides.",
          "Gently flap your knees up and down like butterfly wings.",
          "Try to lower your knees closer to the floor with each gentle push."],
    tips=["Use your elbows on your inner thighs for a gentle extra stretch."],
    mistakes=["Forcing the knees down hard — keep it gentle and progressive."],
    roles=["warmup","cooldown"],pres={"sets":2,"duration_seconds":30,"rest_seconds":10,"tempo":"rhythmic"},
    tags=["kids_friendly","warmup","hip_mobility","flexibility","cute"],pr="mobility",
    noise="quiet",space="low"),

dict(id="kids-ex-0075",slug="dragon-fly-jump",name="Dragon Fly Jump",
    desc="A two-footed jump with a simultaneous spread-arm action where children leap, then in the air flap their arms like a dragonfly — building total-body coordination and vertical power.",
    focus="Power",pm=["quads","glutes","shoulders"],sm=["calves","core"],mp="plyometric",fam="jumping-games",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=5.5,dur=0.7,
    form=["Stand with feet together and arms at sides.",
          "Jump up and in the air rapidly flap your arms 3 times like dragonfly wings.",
          "Land softly on both feet with bent knees.",
          "How many flaps can you fit in one jump?"],
    tips=["Jump high to give yourself more time for the arm flaps in the air."],
    mistakes=["Flapping before leaving the ground — save the flaps for when you're airborne."],
    roles=["main"],pres={"sets":3,"duration_seconds":20,"rest_seconds":20},
    tags=["kids_friendly","plyometric","coordination","games_based","fun"]),

dict(id="kids-ex-0076",slug="robot-march-kids",name="Robot March",
    desc="A stiff, mechanical march where children move with locked joints like a robot — contrasting with natural movement to build body awareness, muscle control, and comic self-expression.",
    focus="Coordination",pm=["quads","hip_flexors"],sm=["core","shoulders"],mp="locomotion",fam="character-movement",
    dr=1,bands=K,mt="warmup",diff="beginner",struct="warmup",wt=30,met=3.5,dur=0.7,
    form=["Stand stiff like a robot and march forward with straight, rigid legs.",
          "Swing your arms in mechanical 90-degree arcs.",
          "Keep your face serious and your movements precise.",
          "After 10 robot steps, become a floppy rag doll (contrast stretch) — then robot again."],
    tips=["Exaggerate the stiffness — the contrast with floppy mode is what makes this work."],
    mistakes=["Moving naturally — the robot must be stiff and mechanical!"],
    roles=["warmup"],pres={"sets":2,"reps":10,"rest_seconds":10,"tempo":"controlled"},
    tags=["kids_friendly","warmup","body_awareness","creative","fun"],pr="mobility"),

dict(id="kids-ex-0077",slug="volcano-jump",name="Volcano Jump",
    desc="A dramatic squat-to-explosive-jump sequence where children pretend to be a volcano building up pressure before erupting upward — using narrative pacing to develop eccentric loading and explosive power.",
    focus="Power",pm=["quads","glutes","calves"],sm=["core"],mp="plyometric",fam="jumping-games",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=6.0,dur=0.6,
    form=["Stand with feet shoulder-width apart, arms crossed at chest.",
          "Slowly, slowly lower into a deep squat — the volcano is building pressure...",
          "When fully low, explode upward with arms bursting overhead — BOOM! You erupted!",
          "Land softly and rebuild for the next eruption."],
    tips=["The slower the squat, the more power in the eruption."],
    mistakes=["Rushing the descent — slow build creates the dramatic (and powerful) jump."],
    roles=["main"],pres={"sets":3,"reps":6,"rest_seconds":20,"tempo":"contrast"},
    tags=["kids_friendly","plyometric","games_based","power","narrative","fun"]),

dict(id="kids-ex-0078",slug="tick-tock-side-step",name="Tick-Tock Side Step",
    desc="A rhythmic lateral stepping exercise set to a tick-tock metronome count — step right on tick, step left on tock — developing rhythmic coordination, lateral agility, and listening skills.",
    focus="Coordination",pm=["glutes","quads","calves"],sm=["core"],mp="locomotion",fam="rhythm-drills",
    dr=1,bands=K,mt="warmup",diff="beginner",struct="warmup",wt=30,met=3.5,dur=0.7,
    form=["Stand with feet together. Leader counts 'TICK-TOCK' in a steady beat.",
          "On TICK: step your right foot out to the right, then bring left to meet it.",
          "On TOCK: step left foot out to the left, then bring right to meet it.",
          "Keep perfect rhythm — the goal is matching movement to the beat."],
    tips=["Start slow — accuracy to the beat matters more than speed."],
    mistakes=["Losing the rhythm — stop and restart slowly if you fall off beat."],
    roles=["warmup"],pres={"sets":3,"duration_seconds":20,"rest_seconds":10,"tempo":"rhythmic"},
    tags=["kids_friendly","warmup","rhythm","coordination","listening"],pr="mobility"),

dict(id="kids-ex-0079",slug="cloud-jump-soft-landing",name="Cloud Jump Soft Landing",
    desc="A mindful jump-and-land exercise where children are told the floor is a cloud and must land as softly as if landing on a cloud — reinforcing quiet, controlled landing mechanics through imagination.",
    focus="Power",pm=["quads","glutes","calves"],sm=["core","hamstrings"],mp="plyometric",fam="jumping-games",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=5.0,dur=0.6,
    form=["The floor is now a cloud — land so softly the cloud doesn't bounce.",
          "Jump from two feet and focus entirely on making no sound when you land.",
          "Bend your knees deeply to absorb — the softer the landing, the better.",
          "10 cloud jumps then listen: how quiet were they?"],
    tips=["Land toe-ball-heel in quick succession to spread the impact."],
    mistakes=["Landing flat-footed with a thud — soften through the ankle first."],
    roles=["main"],pres={"sets":3,"reps":10,"rest_seconds":20,"tempo":"controlled"},
    tags=["kids_friendly","plyometric","landing_mechanics","mindful","fun"]),

dict(id="kids-ex-0080",slug="thunderstorm-run",name="Thunderstorm Run",
    desc="A games-based cardio drill where different weather events trigger different movements — thunder: stomp in place, lightning: sprint, rain: light jog, sun: slow walk — building cardiovascular fitness through reactive variety.",
    focus="Cardio",pm=["quads","glutes","calves"],sm=["core","hamstrings"],mp="locomotion",fam="games-based-movement",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=6.5,dur=2.0,
    form=["Leader shouts a weather event.",
          "THUNDER: stomp feet as fast as possible on the spot.",
          "LIGHTNING: sprint in any direction.",
          "RAIN: light jog, arms making rain-drop shapes.",
          "SUN: slow walk, arms open wide."],
    tips=["Transitions between weather types are where the real fitness happens — be quick!"],
    mistakes=["Only doing one intensity all the way through — vary with each call."],
    roles=["main"],pres={"sets":1,"duration_seconds":120,"rest_seconds":30},
    tags=["kids_friendly","games_based","cardio","reaction","creative","fun"]),

dict(id="kids-ex-0081",slug="jumping-jack-animals",name="Jumping Jack Animals",
    desc="A variation of jumping jacks where children change the arm shape to mimic different animals on each call — eagle wings (arms wide), crab claws (arms bent), octopus (arms wavy) — adding cognitive engagement.",
    focus="Cardio",pm=["quads","glutes","shoulders","calves"],sm=["core"],mp="plyometric",fam="jumping-games",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=5.5,dur=1.0,
    form=["Start doing regular jumping jacks.",
          "EAGLE: keep doing the leg action but spread arms wide on every jump.",
          "CRAB: bend elbows and click claws together overhead.",
          "OCTOPUS: wave all eight arms (two real, six imaginary) wildly.",
          "Swap animal on every call!"],
    tips=["The sillier the animal, the more fun — commit to the character!"],
    mistakes=["Only moving the legs — the arm variation is what makes this unique."],
    roles=["warmup","main"],pres={"sets":2,"duration_seconds":30,"rest_seconds":20},
    tags=["kids_friendly","cardio","creative","games_based","cognitive","fun"]),

dict(id="kids-ex-0082",slug="freeze-balance-challenge",name="Freeze Balance Challenge",
    desc="An active balance game where children dance or run freely then freeze on a signal in whatever position they are — holding the freeze steady. Develops reactive stability and proprioception.",
    focus="Balance",pm=["core","calves","glutes"],sm=["quads"],mp="hold",fam="games-based-movement",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=4.5,dur=1.5,
    form=["Move freely — dance, run, skip — whatever you want.",
          "On the signal (clap or whistle): FREEZE in your exact position.",
          "Hold perfectly still for 5 seconds — even if you're on one foot!",
          "Release and move again. Try to land in harder positions each time."],
    tips=["Try to land in a challenging pose before the signal — it's more fun!"],
    mistakes=["Moving after the signal — the freeze is instant."],
    roles=["warmup","main"],pres={"sets":1,"duration_seconds":90,"rest_seconds":15},
    tags=["kids_friendly","games_based","balance","reaction","fun"]),

dict(id="kids-ex-0083",slug="jump-turn-180",name="Jump Turn 180",
    desc="A rotational jump where children jump and spin 180 degrees in the air to land facing the opposite direction — building rotational power, spatial orientation, and landing confidence.",
    focus="Coordination",pm=["quads","glutes","calves"],sm=["core"],mp="plyometric",fam="jumping-games",
    dr=2,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=5.5,dur=0.6,
    form=["Stand facing forward, feet hip-width.",
          "Bend knees, swing arms back, then jump and twist your body 180 degrees.",
          "Land facing the opposite way — soft knees!",
          "Jump and spin back to face the start. 5 turns each direction."],
    tips=["Spot a point on the wall to help orient your rotation."],
    mistakes=["Not completing the 180 — commit to the full rotation."],
    roles=["main"],pres={"sets":3,"reps":6,"rest_seconds":20},
    tags=["kids_friendly","plyometric","rotational","coordination","fun"]),

dict(id="kids-ex-0084",slug="echo-run",name="Echo Run",
    desc="A movement-mirroring cardio game where children copy the leader's exact running pattern — same pace, same path, same arms — building attentional focus, cardiovascular fitness, and movement observation.",
    focus="Cardio",pm=["quads","glutes","calves"],sm=["core"],mp="locomotion",fam="games-based-movement",
    dr=1,bands=K,mt="cardio",diff="beginner",struct="main",wt=30,met=6.0,dur=2.0,
    form=["One child is the leader and runs in any pattern — zigzag, spiral, stop-start.",
          "All others follow as closely as possible, mimicking every move.",
          "After 45 seconds, a new child leads.",
          "The best echo is the one who is closest and most accurate."],
    tips=["Echoes: watch the whole body, not just the feet."],
    mistakes=["Running on autopilot — true echo requires constant attention."],
    roles=["main"],pres={"sets":1,"duration_seconds":120,"rest_seconds":30},
    tags=["kids_friendly","games_based","cardio","cognitive","cooperative","fun"]),

dict(id="kids-ex-0085",slug="alphabet-body-pose",name="Alphabet Body Pose",
    desc="Children use their body to form the shapes of letters — 'A' is wide stance arms over head, 'X' is starfish, 'O' is a squat — blending literacy with creative body-shaping and static strength.",
    focus="Coordination",pm=["core","shoulders","quads"],sm=["back","glutes"],mp="hold",fam="character-movement",
    dr=1,bands=K,mt="warmup",diff="beginner",struct="warmup",wt=30,met=2.5,dur=1.0,
    form=["Leader calls a letter.",
          "Children have 3 seconds to shape their body into that letter.",
          "Hold for 3 seconds — show your letter to the group.",
          "Try: X (starfish), O (round squat), T (arms wide), L (one leg out), V (wide squat arms up)."],
    tips=["Some letters need partners to make — try A, H, or W with a friend."],
    mistakes=["Making approximate shapes — try to be accurate and hold still."],
    roles=["warmup"],pres={"sets":2,"duration_seconds":60,"rest_seconds":10},
    tags=["kids_friendly","warmup","creative","body_awareness","literacy","fun"],pr="mobility"),

# ── 17 KIDS+TWEENS ────────────────────────────────────────────────────────────
dict(id="kids-ex-0086",slug="shuttle-run-circuit",name="Shuttle Run Circuit",
    desc="A classic 5-10-5 shuttle sprint where children run to a near cone, back to start, then to a far cone and back — building acceleration, deceleration, and change-of-direction speed.",
    focus="Cardio",pm=["quads","glutes","hamstrings","calves"],sm=["core"],mp="locomotion",fam="agility-drills",
    dr=2,bands=KT,mt="cardio",diff="beginner",struct="main",wt=40,met=9.0,dur=0.4,
    form=["Place two cones 5 m and 10 m from the start line.",
          "Sprint to the 5 m cone, touch it, sprint back to start, sprint to the 10 m cone, sprint back.",
          "Rest 30 seconds. Try to beat your time on each set."],
    tips=["Plant your outside foot when turning to change direction fast."],
    mistakes=["Slowing before the cone — decelerate and turn simultaneously."],
    roles=["main"],pres={"sets":4,"reps":1,"rest_seconds":30,"tempo":"maximal"},
    tags=["kids_friendly","cardio","agility","speed","timed","athletic"],
    ts=["basketball","soccer","football","tennis"]),

dict(id="kids-ex-0087",slug="jump-rope-simulation",name="Jump Rope Simulation",
    desc="A jump rope movement performed without a rope — the same two-footed or alternating-foot bounce pattern — building calf endurance, jump rhythm, and cardiovascular capacity anywhere.",
    focus="Cardio",pm=["calves","quads"],sm=["core","shoulders"],mp="plyometric",fam="jumping-games",
    dr=1,bands=KT,mt="cardio",diff="beginner",struct="main",wt=40,met=8.0,dur=1.0,
    form=["Imagine holding a jump rope. Rotate your wrists in small circles.",
          "Bounce on both feet with small, quick hops (2–3 cm off ground).",
          "Stay on the balls of your feet the whole time.",
          "Progress to alternating feet (one-foot rhythm) for more challenge."],
    tips=["Keep hops very small — big jumps burn out your calves quickly."],
    mistakes=["Jumping too high — efficiency beats height."],
    roles=["warmup","main"],pres={"sets":3,"duration_seconds":30,"rest_seconds":20},
    tags=["kids_friendly","cardio","calf_endurance","rhythm","no_equipment"],
    ts=["boxing","basketball"]),

dict(id="kids-ex-0088",slug="mountain-explorer-crawl",name="Mountain Explorer Crawl",
    desc="A narrative locomotion circuit where children crawl under obstacles, leap over creeks, and balance on rocks (imagined or real cones) — combining multiple movement patterns with storytelling.",
    focus="Cardio",pm=["quads","glutes","shoulders","core"],sm=["calves","back"],mp="locomotion",fam="games-based-movement",
    dr=1,bands=KT,mt="cardio",diff="beginner",struct="main",wt=40,met=5.5,dur=2.0,
    form=["Set up a simple obstacle course or imagine one.",
          "Crawl under the low branch (low bear crawl).",
          "Jump over the creek (two-foot jump).",
          "Balance across the log (tightrope walk).",
          "Sprint to the summit (10 m sprint)!"],
    tips=["Narrate the journey out loud — it makes transitions quicker and more fun."],
    mistakes=["Skipping elements — do every challenge in sequence."],
    roles=["main"],pres={"sets":2,"reps":3,"rest_seconds":30},
    tags=["kids_friendly","games_based","cardio","multi_movement","narrative","fun"]),

dict(id="kids-ex-0089",slug="shadow-boxing-circuit-kids",name="Shadow Boxing Circuit",
    desc="A structured shadow boxing sequence where children throw jab-cross-hook combinations in the air — building upper body coordination, core rotation, and aerobic fitness through boxing-inspired movement.",
    focus="Cardio",pm=["shoulders","core"],sm=["chest","back","quads"],mp="locomotion",fam="boxing-drills",
    dr=2,bands=KT,mt="cardio",diff="beginner",struct="main",wt=40,met=6.5,dur=1.0,
    form=["Stand in an athletic stance — left foot forward (right if left-handed).",
          "Jab: quick straight left punch forward.",
          "Cross: rotating straight right punch.",
          "Hook: bent-arm horizontal swing.",
          "Combo: jab-cross-hook for 30 seconds, then rest."],
    tips=["Rotate your back foot as you throw the cross — power comes from the ground up."],
    mistakes=["Punching with arms only — rotate the hips and core with every shot."],
    roles=["main"],pres={"sets":4,"duration_seconds":30,"rest_seconds":20},
    tags=["kids_friendly","cardio","boxing","coordination","upper_body"],
    ts=["boxing"]),

dict(id="kids-ex-0090",slug="gallop-forward",name="Gallop Forward",
    desc="A locomotion movement where children lead with the same foot and bound forward in a galloping pattern — developing rhythm, single-leg push-off power, and locomotor variety.",
    focus="Coordination",pm=["quads","glutes","calves"],sm=["core","hip_flexors"],mp="locomotion",fam="locomotor-skills",
    dr=1,bands=KT,mt="cardio",diff="beginner",struct="warmup",wt=40,met=5.5,dur=0.7,
    form=["Start with right foot forward — this is your lead foot.",
          "Step-hop on the right foot, bringing the left foot up to meet it.",
          "Keep stepping-hopping with the right foot leading — like a horse gallop!",
          "After 10 m, switch to the left foot leading."],
    tips=["Listen for the rhythm: STEP-HOP, STEP-HOP, STEP-HOP — like a horse's canter."],
    mistakes=["Alternating lead feet — a gallop always leads with the same foot."],
    roles=["warmup"],pres={"sets":2,"duration_seconds":20,"rest_seconds":15},
    tags=["kids_friendly","warmup","locomotor","rhythm","fun"]),

dict(id="kids-ex-0091",slug="lateral-gallop",name="Lateral Gallop",
    desc="A side-to-side galloping movement where children step-slide laterally, staying low and athletic — building lateral locomotor skills, inner thigh mobility, and coordination.",
    focus="Coordination",pm=["glutes","quads","calves","adductors"],sm=["core"],mp="locomotion",fam="locomotor-skills",
    dr=1,bands=KT,mt="cardio",diff="beginner",struct="warmup",wt=40,met=5.5,dur=0.7,
    form=["Face forward and step your right foot wide to the right.",
          "Slide your left foot to meet it, staying in a slight squat.",
          "Continue the step-slide sideways for 8–10 metres.",
          "Reverse direction — lead with the left for 8–10 metres back."],
    tips=["Stay low — don't stand up between steps."],
    mistakes=["Crossing feet — step and slide, don't cross."],
    roles=["warmup"],pres={"sets":2,"duration_seconds":20,"rest_seconds":15},
    tags=["kids_friendly","warmup","lateral","locomotor","agility"]),

dict(id="kids-ex-0092",slug="zigzag-sprint-cones",name="Zigzag Sprint",
    desc="A change-of-direction sprint through a zigzag cone pattern — building acceleration, deceleration, agility, and lateral cutting speed in a beginner-friendly format.",
    focus="Cardio",pm=["quads","glutes","calves","hamstrings"],sm=["core"],mp="locomotion",fam="agility-drills",
    dr=2,bands=KT,mt="cardio",diff="beginner",struct="main",wt=40,met=8.5,dur=0.5,
    form=["Set up 5 cones in a zigzag pattern (1.5–2 m apart each).",
          "Sprint from cone to cone, cutting sharply at each one.",
          "Plant the outside foot at each cone and push off hard.",
          "Time yourself — try to beat your previous best."],
    tips=["Attack each cone — don't slow down in anticipation, decelerate AT the cone."],
    mistakes=["Running in a curve instead of sharp angles — hit the cone precisely."],
    roles=["main"],pres={"sets":4,"reps":2,"rest_seconds":30,"tempo":"maximal"},
    tags=["kids_friendly","cardio","agility","speed","sprint","athletic"],
    ts=["soccer","basketball","football","tennis"]),

dict(id="kids-ex-0093",slug="skip-and-clap",name="Skip and Clap",
    desc="A rhythm coordination drill where children skip in place and clap on every third hop — integrating auditory rhythm with locomotor movement and bilateral coordination.",
    focus="Coordination",pm=["calves","quads","hip_flexors"],sm=["core","shoulders"],mp="locomotion",fam="rhythm-drills",
    dr=1,bands=KT,mt="warmup",diff="beginner",struct="warmup",wt=40,met=4.5,dur=0.7,
    form=["Skip in place, bringing alternate knees up.",
          "Count: 1-2-3 CLAP, 1-2-3 CLAP.",
          "Clap overhead on every third hop.",
          "Start slow, then build to a fast rhythm."],
    tips=["Say the count out loud until the rhythm is automatic."],
    mistakes=["Clapping on every hop — the off-beat clap is what makes this a coordination drill."],
    roles=["warmup"],pres={"sets":3,"duration_seconds":20,"rest_seconds":15},
    tags=["kids_friendly","warmup","rhythm","coordination","bilateral"]),

dict(id="kids-ex-0094",slug="zigzag-balance-beam",name="Zigzag Balance Beam",
    desc="Children walk in a zigzag heel-to-toe pattern along a taped line that changes direction every 1 m — combining tightrope balance with directional changes and sustained attention.",
    focus="Balance",pm=["core","calves"],sm=["glutes","hip_abductors"],mp="locomotion",fam="balance-challenges",
    dr=1,bands=KT,mt="warmup",diff="beginner",struct="warmup",wt=40,met=2.5,dur=0.7,
    form=["Tape a zigzag pattern on the floor — changes direction every 1 m.",
          "Walk heel-to-toe along the pattern without stepping off.",
          "Arms out wide for balance.",
          "Turn at each corner with a deliberate pivot — don't step off the tape."],
    tips=["Slow right down at the corners — precision beats speed here."],
    mistakes=["Rushing straight sections so fast you miss the corners."],
    roles=["warmup"],pres={"sets":3,"reps":2,"rest_seconds":15},
    tags=["kids_friendly","balance","warmup","proprioception","precision"],pr="mobility"),

dict(id="kids-ex-0095",slug="fire-hydrant-circuit-kids",name="Fire Hydrant Circuit",
    desc="A sequence of fire hydrant movements performed on all fours — hip circles, kickbacks, and side lifts — building glute and hip stability in a playful animal-named circuit.",
    focus="Strength",pm=["glutes"],sm=["core","back"],mp="isolation",fam="glute-activation",
    dr=1,bands=KT,mt="strength",diff="beginner",struct="main",wt=40,met=3.0,dur=1.0,
    form=["Start on hands and knees, back flat.",
          "Fire Hydrant: lift right knee out to the side (like a dog at a hydrant) x10.",
          "Hip Circle: rotate that knee in a full circle x5 each way.",
          "Kickback: extend the right leg straight back x10.",
          "Switch to left leg and repeat."],
    tips=["Keep back flat throughout — don't rotate the spine as the leg lifts."],
    mistakes=["Rotating the hips to get more range — keep them square."],
    roles=["warmup","main"],pres={"sets":2,"reps":10,"rest_seconds":20,"tempo":"controlled"},
    tags=["kids_friendly","glutes","hip_stability","strength","warmup"],
    ts=["soccer","running","basketball"]),

dict(id="kids-ex-0096",slug="running-man-drill",name="Running Man Drill",
    desc="An in-place high-knee running drill performed in slow motion, each stride exaggerated and held — teaching proper running mechanics (arm drive, knee lift, foot strike) before speed is added.",
    focus="Coordination",pm=["quads","hip_flexors","calves"],sm=["core","glutes"],mp="locomotion",fam="running-drills",
    dr=1,bands=KT,mt="warmup",diff="beginner",struct="warmup",wt=40,met=4.0,dur=0.7,
    form=["Lift your right knee to hip height — hold for 1 second.",
          "Drive your left arm forward simultaneously — hold 1 second.",
          "Lower right leg and raise left knee, drive right arm forward.",
          "Alternate slowly, then progressively faster each set."],
    tips=["Your arm should reach forward (not sideways) at 90 degrees, opposite to the knee."],
    mistakes=["Crossing arms in front of the body — keep them driving straight forward."],
    roles=["warmup"],pres={"sets":3,"duration_seconds":20,"rest_seconds":15,"tempo":"progressive"},
    tags=["kids_friendly","warmup","running_mechanics","coordination","athletic"],
    ts=["running","soccer","basketball","football"]),

dict(id="kids-ex-0097",slug="plank-circuit-mini",name="Plank Circuit Mini",
    desc="A mini-circuit cycling through three plank variations — high plank, forearm plank, and side plank — spending 15 seconds in each position for a total core conditioning sequence.",
    focus="Strength",pm=["core"],sm=["shoulders","glutes","back"],mp="hold",fam="plank-variations",
    dr=2,bands=KT,mt="strength",diff="beginner",struct="main",wt=40,met=3.5,dur=1.5,
    hold=True,hs=15,
    form=["High plank: hands under shoulders, body straight — 15 sec.",
          "Lower to forearm plank — 15 sec.",
          "Rotate to right side plank — 15 sec.",
          "Rotate to left side plank — 15 sec.",
          "That is one circuit. Rest 30 sec and repeat."],
    tips=["Stay tight throughout the transitions — don't let form drop between positions."],
    mistakes=["Sagging hips in any position — brace the core before each transition."],
    roles=["main"],pres={"sets":3,"duration_seconds":60,"rest_seconds":30,"tempo":"static"},
    tags=["kids_friendly","core","strength","circuit","no_equipment"]),

dict(id="kids-ex-0098",slug="partner-push-balance",name="Partner Push Balance",
    desc="A cooperative balance drill where two children face each other, press palms together, and try to make the other person step by pushing — building shoulder strength, core stability, and force production.",
    focus="Strength",pm=["shoulders","chest","core"],sm=["quads","back"],mp="hold",fam="cooperative-games",
    dr=2,bands=KT,mt="strength",diff="beginner",struct="main",wt=40,met=3.5,dur=0.7,
    form=["Face your partner with feet hip-width, arms bent, palms touching.",
          "Both try to push the other person off balance by pressing through palms.",
          "You win by making your partner step — you lose if YOU step.",
          "3 rounds of 20 seconds."],
    tips=["Keep your centre of gravity low — bend knees slightly."],
    mistakes=["Lunging forward — use steady pushing pressure, not a single lunge."],
    roles=["main"],pres={"sets":3,"duration_seconds":20,"rest_seconds":15},
    tags=["kids_friendly","cooperative","balance","strength","fun"]),

dict(id="kids-ex-0099",slug="ninja-obstacle-sprint",name="Ninja Obstacle Sprint",
    desc="A games-based agility sprint with obstacle actions — roll, crawl, sprint, jump — cycling through them in sequence like a ninja assault course, building all-round movement competency.",
    focus="Cardio",pm=["quads","glutes","shoulders","core"],sm=["calves","back"],mp="locomotion",fam="games-based-movement",
    dr=2,bands=KT,mt="cardio",diff="beginner",struct="main",wt=40,met=7.5,dur=1.5,
    form=["Sprint to cone 1 (5 m).",
          "Drop and do a forward roll or log roll to cone 2.",
          "Bear crawl to cone 3.",
          "Two-foot jump over the last marker and sprint to finish.",
          "Rest 30 sec and go again."],
    tips=["Commit to each obstacle fully — half-effort on the crawl slows your time."],
    mistakes=["Slowing to a walk on the crawl — maintain intensity throughout."],
    roles=["main"],pres={"sets":3,"reps":2,"rest_seconds":30},
    tags=["kids_friendly","games_based","cardio","agility","multi_movement","fun"]),

dict(id="kids-ex-0100",slug="bear-crab-transition",name="Bear-Crab Transition",
    desc="A floor-based movement drill cycling between bear crawl position (face down) and crab walk position (face up) — building all-around core strength, shoulder stability, and body-rotation awareness.",
    focus="Strength",pm=["core","shoulders"],sm=["glutes","triceps","quads"],mp="mobility",fam="ground-movement",
    dr=2,bands=KT,mt="strength",diff="beginner",struct="main",wt=40,met=4.5,dur=0.8,
    form=["Start in bear crawl: face down, hands and feet on floor, hips at knee height.",
          "Rotate to crab: keep hands and feet planted, flip to face up.",
          "Hold crab for 3 seconds, then rotate back to bear.",
          "That is one rep — complete 8 transitions."],
    tips=["Move one limb at a time during the flip — don't just flop over."],
    mistakes=["Rushing the flip and losing tension — controlled rotation is the goal."],
    roles=["main"],pres={"sets":3,"reps":8,"rest_seconds":30,"tempo":"controlled"},
    tags=["kids_friendly","core","upper_body","strength","transition","fun"]),

dict(id="kids-ex-0101",slug="dance-fitness-kids",name="Dance Fitness Combo",
    desc="A structured freestyle dance cardio sequence — step-touch, grapevine, body roll, and kick-ball-change — building cardiovascular fitness, rhythm, and self-expression through age-appropriate dance.",
    focus="Cardio",pm=["quads","glutes","calves"],sm=["core","shoulders"],mp="locomotion",fam="dance-fitness",
    dr=1,bands=KT,mt="cardio",diff="beginner",struct="main",wt=40,met=6.0,dur=1.5,
    form=["Step-touch x4 right then x4 left (step side, tap other foot in).",
          "Grapevine: step right, cross left behind, step right, tap — then reverse x2.",
          "Body roll: feet planted, wave your body from head to hips x4.",
          "Kick-ball-change: kick right, step, change weight x4.",
          "Cycle all four and repeat!"],
    tips=["Music makes this 10x better — put on something with a strong beat."],
    mistakes=["Standing still on the ball-change — it should be quick and rhythmic."],
    roles=["main"],pres={"sets":2,"duration_seconds":90,"rest_seconds":30},
    tags=["kids_friendly","cardio","dance","rhythm","fun","expressive"],noise="loud"),

dict(id="kids-ex-0102",slug="tunnel-crawl-sprint",name="Tunnel Crawl Sprint",
    desc="A two-phase movement drill where one child makes a tunnel shape (downward dog position) while another crawls through — then both sprint to the next station, combining cooperative movement and cardio.",
    focus="Cardio",pm=["shoulders","core","quads","hamstrings"],sm=["back","calves"],mp="locomotion",fam="cooperative-games",
    dr=2,bands=KT,mt="cardio",diff="beginner",struct="main",wt=40,met=6.0,dur=1.0,
    form=["Partner A holds downward dog position — creating a tunnel.",
          "Partner B crawls through the tunnel (commando-style).",
          "Once through, B taps a cone 5 m away and sprints back.",
          "A counts to 10 in downward dog, then they swap.",
          "3 rounds each."],
    tips=["Tunnels: keep hips high so the crawler can get under cleanly."],
    mistakes=["Tunnel collapsing before the crawler is through — hold firm."],
    roles=["main"],pres={"sets":3,"reps":2,"rest_seconds":30},
    tags=["kids_friendly","cooperative","cardio","upper_body","fun"]),

# ── 15 TWEENS+TEENS dynamic warmup ────────────────────────────────────────────
dict(id="kids-ex-0103",slug="leg-swing-forward-back",name="Leg Swing Forward-Back",
    desc="A standing dynamic hip flexor and hamstring mobilisation where the leg is swung forward and back in a controlled pendulum — a standard athletic warmup for the posterior and anterior chain.",
    focus="Flexibility",pm=["hamstrings","hip_flexors"],sm=["glutes","core"],mp="mobility",fam="dynamic-warmup",
    dr=1,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=2.5,dur=0.5,
    ps=True,uni=True,
    form=["Stand on your right foot next to a wall for support.",
          "Swing the left leg forward as high as comfortable, keeping it straight.",
          "Let it swing back behind you — relaxed but controlled.",
          "Gradually increase range over 10–15 swings, then switch legs."],
    tips=["Let gravity do the back swing — don't force it."],
    mistakes=["Bending the swinging knee — keep it long like a pendulum."],
    roles=["warmup"],pres={"sets":2,"reps":15,"rest_seconds":10,"tempo":"rhythmic"},
    tags=["dynamic_warmup","hip_mobility","hamstrings","athletic","warmup"],
    ts=["running","soccer","football","basketball"],pr="mobility",noise="quiet",space="low"),

dict(id="kids-ex-0104",slug="leg-swing-lateral",name="Leg Swing Side to Side",
    desc="A lateral hip abductor and adductor dynamic stretch where the leg swings across the body and out to the side — mobilising the hip joint in the frontal plane as part of an athletic warmup.",
    focus="Flexibility",pm=["hip_abductors","adductors"],sm=["glutes","core"],mp="mobility",fam="dynamic-warmup",
    dr=1,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=2.5,dur=0.5,
    ps=True,uni=True,
    form=["Stand sideways to a wall, right hand on the wall for support.",
          "Swing the left leg across the body to the right, then out to the left.",
          "Let the momentum increase gradually — controlled amplitude.",
          "15 swings, then turn around and swing the right leg."],
    tips=["Keep hips square to the front — don't rotate them with the leg."],
    mistakes=["Hiking the hip — keep both hip bones level throughout the swing."],
    roles=["warmup"],pres={"sets":2,"reps":15,"rest_seconds":10,"tempo":"rhythmic"},
    tags=["dynamic_warmup","hip_mobility","adductors","athletic","warmup"],
    ts=["soccer","basketball","running"],pr="mobility",noise="quiet",space="low"),

dict(id="kids-ex-0105",slug="hip-90-90-flow",name="Hip 90/90 Flow",
    desc="A seated hip mobility drill where athletes rotate between external and internal rotation in the 90/90 position — systematically opening both hips through their full rotational range.",
    focus="Flexibility",pm=["glutes","hip_flexors"],sm=["adductors","back"],mp="mobility",fam="hip-mobility",
    dr=2,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=2.2,dur=0.8,
    form=["Sit with your right leg in front at 90 degrees and left leg behind at 90 degrees.",
          "Hold for 30 seconds, feeling the stretch in both hips.",
          "Lift your hips, swing both legs to the other side — now right leg is behind.",
          "Hold for 30 seconds. Continue flowing for 5 transitions."],
    tips=["Try to sit up tall in each position — don't collapse the torso."],
    mistakes=["Forcing the hip down — let it find its natural position and breathe."],
    roles=["warmup"],pres={"sets":2,"reps":5,"rest_seconds":15,"tempo":"slow"},
    tags=["dynamic_warmup","hip_mobility","flexibility","athletic","rotation"],
    ts=["golf","basketball","soccer"],pr="mobility",noise="quiet",space="low"),

dict(id="kids-ex-0106",slug="thoracic-rotation-squat",name="Thoracic Rotation in Squat",
    desc="A deep squat hold combined with thoracic spine rotation — athletes hold the bottom of a squat and rotate their upper body to open the thoracic spine, a key warmup for rotational sports.",
    focus="Flexibility",pm=["back","core"],sm=["glutes","shoulders","hips"],mp="mobility",fam="dynamic-warmup",
    dr=2,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=2.5,dur=0.7,
    form=["Hold a deep squat position, hands in prayer or holding ankles.",
          "Place your right elbow on your right inner knee for support.",
          "Rotate your left arm up toward the ceiling, following with your gaze.",
          "Hold 2 seconds, lower, then rotate right. 5 each side."],
    tips=["Use the deep squat as a lever — the more anchored the hips, the bigger the rotation."],
    mistakes=["Rotating from the lower back — the movement should come from the mid-back."],
    roles=["warmup"],pres={"sets":2,"reps":5,"rest_seconds":15,"tempo":"controlled"},
    tags=["dynamic_warmup","thoracic_rotation","flexibility","warmup","rotation"],
    ts=["golf","tennis","baseball","boxing"],pr="mobility",noise="quiet",space="low"),

dict(id="kids-ex-0107",slug="ankle-circle-warmup",name="Ankle Circle Warmup",
    desc="A seated or standing ankle joint mobilisation where full circles are drawn with the foot — essential pre-activity warmup for the ankle joint before jumping, running, or lateral movement.",
    focus="Flexibility",pm=["calves"],sm=["peroneals","tibialis"],mp="mobility",fam="joint-mobility",
    dr=1,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=1.8,dur=0.4,
    ps=True,
    form=["Sit or stand on one foot, lifting the other just off the floor.",
          "Slowly draw the biggest possible circle with your toes — 10 clockwise.",
          "Then 10 anti-clockwise.",
          "Switch feet and repeat."],
    tips=["Make the circles as large as possible — maximise the ankle's range."],
    mistakes=["Small circles — most of the benefit comes from reaching the end ranges."],
    roles=["warmup"],pres={"sets":2,"reps":10,"rest_seconds":10,"tempo":"slow"},
    tags=["dynamic_warmup","ankle_mobility","joint_prep","warmup"],
    ts=["running","soccer","basketball","football"],pr="mobility",noise="quiet",space="low"),

dict(id="kids-ex-0108",slug="kneeling-hip-flexor-mob",name="Kneeling Hip Flexor Mobilisation",
    desc="A dynamic lunge-based hip flexor stretch where athletes in a half-kneeling position drive the hip forward and back repeatedly to actively mobilise the iliopsoas — key before sprinting or jumping.",
    focus="Flexibility",pm=["hip_flexors"],sm=["glutes","core","quads"],mp="mobility",fam="dynamic-warmup",
    dr=1,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=2.8,dur=0.5,
    ps=True,
    form=["Kneel on your right knee, left foot forward in a lunge.",
          "Keep torso upright and squeeze your right glute.",
          "Drive hips forward until you feel a stretch in the right hip flexor.",
          "Hold 2 seconds, return, repeat 10 times, then switch sides."],
    tips=["Posterior pelvic tilt (tuck the tailbone) deepens the stretch."],
    mistakes=["Leaning forward instead of driving the hip forward."],
    roles=["warmup"],pres={"sets":2,"reps":10,"rest_seconds":15,"tempo":"controlled"},
    tags=["dynamic_warmup","hip_flexor","flexibility","sprint_prep","warmup"],
    ts=["running","soccer","football","basketball"],pr="mobility",noise="quiet",space="low"),

dict(id="kids-ex-0109",slug="worlds-greatest-stretch",name="World's Greatest Stretch",
    desc="A multi-joint dynamic mobility sequence — a forward lunge with thoracic rotation and reach — hitting the hip flexor, thoracic spine, hamstring, and shoulder in one flowing movement.",
    focus="Flexibility",pm=["hip_flexors","back","hamstrings"],sm=["glutes","shoulders","core"],mp="mobility",fam="dynamic-warmup",
    dr=2,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=3.0,dur=0.8,
    ps=True,
    form=["Step your right foot forward into a deep lunge.",
          "Place your right hand inside your right foot on the floor.",
          "Rotate your left arm up to the sky, following with your gaze.",
          "Hold 2 seconds, bring hand down, straighten the front leg (hamstring stretch), then step through.",
          "Continue walking forward, alternating legs — 5 each side."],
    tips=["The whole sequence counts as one 'rep' — don't rush the rotation."],
    mistakes=["Letting the front knee collapse inward during the rotation."],
    roles=["warmup"],pres={"sets":2,"reps":5,"rest_seconds":15,"tempo":"slow"},
    tags=["dynamic_warmup","multi_joint","flexibility","thoracic","warmup"],
    ts=["golf","tennis","baseball","running","soccer"],pr="mobility"),

dict(id="kids-ex-0110",slug="walking-knee-hug",name="Walking Knee Hug",
    desc="A walking dynamic stretch where athletes pull one knee to the chest with each step, briefly balancing on the opposite leg — warming up the hip extensors and single-leg stability simultaneously.",
    focus="Flexibility",pm=["glutes","hamstrings"],sm=["core","calves"],mp="locomotion",fam="dynamic-warmup",
    dr=1,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=3.0,dur=0.5,
    form=["Walk forward. With each step, pull the non-stepping knee to your chest.",
          "Hold for 1 second balancing on the standing leg.",
          "Release and step forward — pull the other knee on the next step.",
          "Cover 10 m with deliberate, controlled pulls."],
    tips=["Rise onto the toes of the standing foot as you hug — increases balance challenge."],
    mistakes=["Not balancing — the single-leg hold is the whole point."],
    roles=["warmup"],pres={"sets":2,"reps":10,"rest_seconds":10,"tempo":"walking"},
    tags=["dynamic_warmup","glutes","balance","locomotor","warmup"],
    ts=["running","soccer","football","basketball"],pr="mobility"),

dict(id="kids-ex-0111",slug="walking-quad-pull",name="Walking Quad Pull",
    desc="A dynamic quad stretch performed while walking — each step, athletes pull the back foot toward the glute and balance momentarily — mobilising the rectus femoris and hip flexor before running or jumping activities.",
    focus="Flexibility",pm=["quads","hip_flexors"],sm=["core","calves"],mp="locomotion",fam="dynamic-warmup",
    dr=1,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=3.0,dur=0.5,
    form=["Walk forward. With each step, grab the ankle of the trailing foot and pull to glute.",
          "Balance on the standing leg for 1 second.",
          "Release and step forward — alternate each step.",
          "Cover 10 m."],
    tips=["Keep the knee pointing straight down, not flared out to the side."],
    mistakes=["Leaning forward to compensate — stay tall and upright."],
    roles=["warmup"],pres={"sets":2,"reps":10,"rest_seconds":10,"tempo":"walking"},
    tags=["dynamic_warmup","quad_stretch","balance","locomotor","warmup"],
    ts=["running","soccer","football"],pr="mobility"),

dict(id="kids-ex-0112",slug="toy-soldier-kick",name="Toy Soldier Kick",
    desc="A walking hamstring stretch where athletes kick one straight leg forward and reach the opposite hand to meet it — dynamically warming up the hamstrings and hip flexors with a classic pre-sprint drill.",
    focus="Flexibility",pm=["hamstrings","hip_flexors"],sm=["core","glutes"],mp="locomotion",fam="dynamic-warmup",
    dr=2,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=3.5,dur=0.5,
    form=["Walk forward with a stiff, mechanical stride.",
          "Kick your right leg straight up in front — keep it straight.",
          "Reach your left hand to meet the right foot.",
          "Lower, step, then kick the left leg and reach the right hand.",
          "Cover 10 m."],
    tips=["Kick as high as comfortable — over time your range will increase."],
    mistakes=["Bending the kicking knee — the stretch is hamstring, not quad."],
    roles=["warmup"],pres={"sets":2,"reps":10,"rest_seconds":10,"tempo":"walking"},
    tags=["dynamic_warmup","hamstrings","sprint_prep","locomotor","warmup"],
    ts=["running","soccer","football","basketball"],pr="mobility"),

dict(id="kids-ex-0113",slug="open-book-stretch",name="Open Book Stretch",
    desc="A side-lying thoracic rotation drill where athletes open the top arm behind them like opening a book — systematically warming up thoracic spine rotation for throwing, swinging, and serving sports.",
    focus="Flexibility",pm=["back"],sm=["shoulders","chest","core"],mp="mobility",fam="thoracic-mobility",
    dr=1,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=2.0,dur=0.6,
    ps=True,
    form=["Lie on your right side with knees stacked at 90 degrees, arms together in front.",
          "Keep your bottom arm still and open the top arm up and over to the left.",
          "Follow it with your gaze — let the thoracic spine rotate, not the lumbar.",
          "Return and repeat 10 times, then switch sides."],
    tips=["Keep the knees stacked — they act as a lumbar anchor so rotation comes from the chest."],
    mistakes=["Letting the knees open — this makes it a hip stretch, not thoracic."],
    roles=["warmup"],pres={"sets":2,"reps":10,"rest_seconds":15,"tempo":"slow"},
    tags=["dynamic_warmup","thoracic_rotation","flexibility","warmup","upper_body"],
    ts=["golf","tennis","baseball","boxing"],pr="mobility",noise="quiet",space="low"),

dict(id="kids-ex-0114",slug="progressive-squat-depth",name="Progressive Squat Depth Warmup",
    desc="A squat mobilisation sequence starting at quarter depth and gradually reaching full depth over 3 sets — systematically warming up the hip, knee, and ankle joints before loaded squat movements.",
    focus="Flexibility",pm=["quads","glutes","hip_flexors"],sm=["hamstrings","calves","back"],mp="mobility",fam="dynamic-warmup",
    dr=1,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=3.0,dur=0.8,
    form=["Set 1: Quarter squat x10 — just a small bend, focus on knees tracking out.",
          "Set 2: Half squat x10 — thighs at 45 degrees.",
          "Set 3: Full squat x10 — thighs at or below parallel.",
          "At the bottom of each rep, press knees apart and feel the depth open up."],
    tips=["Add a 2-second pause at each depth to get the joints warm."],
    mistakes=["Going full depth on set one — the progression is the point."],
    roles=["warmup"],pres={"sets":3,"reps":10,"rest_seconds":15,"tempo":"progressive"},
    tags=["dynamic_warmup","squat_prep","mobility","joints","warmup"],
    ts=["basketball","football","baseball","soccer"],pr="mobility"),

dict(id="kids-ex-0115",slug="cossack-squat-lateral-warmup",name="Cossack Squat Lateral Warmup",
    desc="A dynamic lateral squat warmup that alternates deep side lunges while keeping the other leg straight — warming up adductors, hip external rotators, and ankles in a single flowing movement.",
    focus="Flexibility",pm=["adductors","glutes","quads"],sm=["hamstrings","calves","back"],mp="mobility",fam="dynamic-warmup",
    dr=2,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=3.5,dur=0.7,
    form=["Stand wide (wider than shoulder width), toes angled out 30–45 degrees.",
          "Shift your weight right and lower into a deep right-side squat, left leg straight.",
          "Hold 2 seconds, then shift and lower to the left.",
          "Keep alternating — 5 each side."],
    tips=["The straight leg's toes point up — dorsiflex the ankle for a calf/adductor stretch bonus."],
    mistakes=["Not getting depth — push the knee out to increase squat depth."],
    roles=["warmup"],pres={"sets":2,"reps":5,"rest_seconds":15,"tempo":"slow"},
    tags=["dynamic_warmup","adductors","hip_mobility","lateral","warmup"],
    ts=["soccer","basketball","football","tennis"],pr="mobility"),

dict(id="kids-ex-0116",slug="hip-circle-standing-warmup",name="Hip Circle Standing Warmup",
    desc="A standing hip mobility drill where athletes draw large clockwise and anticlockwise circles with their pelvis in an exaggerated hula motion — lubricating the hip joint before loaded movement.",
    focus="Flexibility",pm=["glutes","hip_flexors"],sm=["core","back"],mp="mobility",fam="hip-mobility",
    dr=1,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=2.2,dur=0.5,
    form=["Stand with feet hip-width and hands on hips.",
          "Push your hips to the right, then back, then left, then forward.",
          "Make each circle as big as you can, like an exaggerated hula hoop.",
          "10 clockwise circles, then 10 anti-clockwise."],
    tips=["Increase the circle size over the first few reps as the joint loosens."],
    mistakes=["Moving the whole torso — isolate the hip movement from the shoulders."],
    roles=["warmup"],pres={"sets":2,"reps":10,"rest_seconds":10,"tempo":"slow"},
    tags=["dynamic_warmup","hip_mobility","warmup","joint_prep"],
    ts=["golf","soccer","tennis","basketball"],pr="mobility",noise="quiet",space="low"),

dict(id="kids-ex-0117",slug="thoracic-extension-hands",name="Thoracic Extension on Hands",
    desc="A floor-based thoracic extension drill where athletes are on all fours and let the mid-back drop and extend toward the floor — reversing the rounded-spine posture common in young athletes and desk users.",
    focus="Flexibility",pm=["back"],sm=["shoulders","core"],mp="mobility",fam="thoracic-mobility",
    dr=1,bands=TT,mt="warmup",diff="beginner",struct="warmup",wt=47,met=2.2,dur=0.5,
    form=["Start on hands and knees, wrists under shoulders.",
          "Hinge through the mid-back — let your chest sink toward the floor and look up slightly.",
          "Hold 3 seconds — feel the chest opening and mid-back extending.",
          "Return to neutral and repeat 10 times."],
    tips=["Imagine your mid-back is a single hinge — keep the lumbar neutral."],
    mistakes=["Extending through the lower back — keep lumbar still, move only the thoracic."],
    roles=["warmup"],pres={"sets":2,"reps":10,"rest_seconds":15,"tempo":"slow"},
    tags=["dynamic_warmup","thoracic_extension","posture","warmup","back_health"],
    ts=["golf","tennis","baseball","rowing"],pr="mobility",noise="quiet",space="low"),
]

def main():
    with open(SRC) as f:
        data=json.load(f)
    before=len(data)
    new_exs=[ex(d) for d in DEFS]
    data.extend(new_exs)
    with open(SRC,'w') as f:
        json.dump(data,f,indent=2)
    print(f"Batch 1 done: {len(new_exs)} entries added, running total {len(data)}/500 (was {before})")

if __name__=='__main__':
    main()
