#!/usr/bin/env python3
"""Batch 3: ~37 sport-gap entries — golf/tennis/soccer for Tweens/Teens."""
import json,os
SRC=os.path.join(os.path.dirname(__file__),'..','data','exercises.json')
SN=("MET values estimated from Compendium of Physical Activities (Ainsworth 2011); "
    "weight assumed 55 kg (Tweens/Teens).")
def ex(d):
    wt=d.get('wt',55);met=d.get('met',4.0);dur=d.get('dur',1.0)
    cpm=round(met*wt/60,1);ce=round(cpm*dur,1)
    role=d.get('pr','strength');pres=d.get('pres',{'sets':3,'reps':10,'rest_seconds':45,'tempo':'controlled'})
    eq=d.get('eq',['bodyweight'])
    return {
        "id":d['id'],"slug":d['slug'],"name":d['name'],"description":d['desc'],
        "level":d.get('level','Beginner'),"primary_focus":d.get('focus','Strength'),
        "body_area":None,"equipment":eq,
        "primary_muscles":d.get('pm',[]),"secondary_muscles":d.get('sm',[]),
        "stabilizer_muscles":d.get('st',[]),"muscles_subregions":d.get('sub',[]),
        "movement_pattern":d['mp'],"family":d.get('fam',d['slug']),
        "difficulty_rank":d.get('dr',2),"workout_roles":d.get('roles',['main']),
        "sports":d.get('sports',[]),"goals":d.get('goals',['improve_performance']),
        "settings":d.get('settings',['home','gym','field']),
        "tags":d.get('tags',[]),
        "contraindications":d.get('contra',[]),
        "narration_script":None,"popularity":None,"variant_of":None,
        "instructions":{"form":d.get('form',['Perform with controlled technique.']),"proTips":d.get('tips',[]),"commonMistakes":d.get('mistakes',[])},
        "classification":{"family":d.get('fam',d['slug']),"isPerSide":d.get('ps',False),
            "unilateral":d.get('uni',False),"energySystem":d.get('es','glycolytic'),
            "kineticChain":d.get('kc','closed'),"planeOfMotion":d.get('plane',['sagittal']),
            "bodyweightOnly":len([e for e in eq if e!='bodyweight'])==0,"difficultyRank":d.get('dr',2),
            "movementPattern":d['mp'],
            "contractionTypes":d.get('ct',['concentric','eccentric']),
            "compoundOrIsolation":d.get('ci','compound')},
        "demands":{"cns":d.get('cns','medium'),"noise":d.get('noise','quiet'),
            "space":d.get('space','low'),"stability":d.get('stab','medium')},
        "prescription":{"isHold":d.get('hold',False),"default":{role:pres},"defaultHoldSeconds":d.get('hs',None)},
        "energy":{"metValue":met,"sourceNote":SN,"durationMinutes":dur,
            "caloriesEstimate":ce,"caloriesPerMinute":cpm,"assumedUserWeightKg":wt,"proteinPostWorkoutG":None},
        "timing":{"repSecondsEstimate":d.get('rs',None),"videoPortraitSeconds":None,"videoLandscapeSeconds":None},
        "media":{"image":{"path":None,"available":False},"videoPortrait":{"path":None,"available":False},"videoLandscape":{"path":None,"available":False}},
        "cv":None,"alternatives":[],"_raw":None,
        "taxonomy":{"age_bands_suggested":d.get('bands',["Tweens","Teens"]),"age_bands_confirmed":None,
            "sports_suggested":d.get('ts',[]),"sports_confirmed":None,
            "position":[],"position_confirmed":None,
            "movement_type":d.get('mt','strength'),"difficulty":d.get('diff','beginner'),
            "structure":d.get('struct','main'),"safety_flags":d.get('flags',[])},
        "review_status":"pending"}

TT=["Tweens","Teens"]

DEFS=[
# ── GOLF (13) ────────────────────────────────────────────────────────────────
dict(id="kids-ex-0168",slug="golf-hip-rotation-drill",name="Golf Hip Rotation Drill",
    desc="A standing drill where athletes rotate the pelvis fully left and right while keeping the upper body relatively still — isolating the hip turn that generates power in the golf downswing and follow-through.",
    focus="Mobility",pm=["core","glutes"],sm=["hip_flexors","back"],st=["calves"],
    sub=["obliques","gluteus maximus","hip rotators"],
    mp="rotation",fam="rotational-core",dr=1,eq=["bodyweight"],
    roles=["warmup"],goals=["improve_rotation","improve_performance","improve_mobility"],
    tags=["golf","rotation","hip_mobility","warmup","sport_specific"],
    form=["Stand in your golf address posture — slight forward lean, knees softly bent.",
          "Cross arms over chest or put hands on hips.",
          "Rotate your hips fully to the right (backswing side), then fully to the left (follow-through).",
          "Keep shoulders relatively stable — this is a HIP rotation drill."],
    tips=["Think of turning a barrel around your spine — keep the axis tall."],
    mistakes=["Swaying laterally instead of rotating — the head should stay still."],
    ts=["golf"],mt="warmup",diff="beginner",struct="warmup",
    met=2.5,pres={"sets":2,"reps":20,"rest_seconds":20,"tempo":"slow"},pr="mobility",rs=2.0),

dict(id="kids-ex-0169",slug="golf-trail-arm-extension",name="Golf Trail Arm Extension Drill",
    desc="An isolated trail-arm drill practising the straightening of the lead arm through the hitting zone — building the neural pattern for a wide, powerful arc by isolating the arm swing without a club.",
    focus="Skill",pm=["shoulders","triceps"],sm=["back","core"],st=[],
    sub=["anterior deltoid","triceps brachii","pectoralis major"],
    mp="push_horizontal",fam="golf-skill-drills",dr=1,eq=["bodyweight"],
    roles=["warmup"],goals=["improve_performance","improve_rotation"],
    tags=["golf","trail_arm","swing_pattern","sport_specific","skill"],
    form=["Stand in address posture. Tuck right (trail) elbow against your body.",
          "Simulate the downswing: rotate your hips and let the right arm extend through impact.",
          "Your right arm should be fully extended at the 'impact' position.",
          "Finish with the right shoulder under your chin."],
    tips=["The extension should feel like throwing a frisbee side-arm — hip first, then arm."],
    mistakes=["Throwing the arm before the hips — always sequence hip rotation first."],
    ts=["golf"],mt="warmup",diff="beginner",struct="warmup",
    met=2.5,pres={"sets":3,"reps":15,"rest_seconds":20,"tempo":"controlled"},pr="mobility",rs=2.0),

dict(id="kids-ex-0170",slug="golf-thoracic-rotation-drill",name="Golf Thoracic Rotation Drill",
    desc="A seated or kneeling thoracic rotation mobility drill — unlocking the mid-back rotation essential for a full golf backswing turn, reducing the compensation patterns that cause slices and back pain in young golfers.",
    focus="Mobility",pm=["back","core"],sm=["shoulders"],st=[],
    sub=["thoracic spine rotators","obliques","rhomboids"],
    mp="rotation",fam="thoracic-mobility",dr=1,eq=["bodyweight"],
    roles=["warmup"],goals=["improve_mobility","improve_rotation","injury_prevention"],
    tags=["golf","thoracic","mobility","rotation","warmup","spine"],
    form=["Kneel on both knees or sit tall in a chair. Place hands behind your head.",
          "Rotate your upper body to the right as far as comfortable.",
          "Return to centre and rotate left.",
          "Move slowly and deliberately — feel the mid-back opening."],
    tips=["Keep the hips facing forward — rotate ONLY the thoracic spine."],
    mistakes=["Rotating at the hips — this is a thoracic-only drill."],
    ts=["golf","tennis","baseball"],mt="warmup",diff="beginner",struct="warmup",
    met=2.0,pres={"sets":2,"reps":10,"rest_seconds":15,"tempo":"slow"},pr="mobility",rs=3.0),

dict(id="kids-ex-0171",slug="golf-split-squat-hip-load",name="Golf Split-Squat Hip Load",
    desc="A split squat in golf address posture with emphasis on the rear hip — training the posterior hip loading (X-factor stretch) that coils power at the top of the backswing for young golfers.",
    focus="Strength",pm=["glutes","quads"],sm=["hamstrings","core"],st=["calves"],
    sub=["gluteus maximus","gluteus medius","quadriceps"],
    mp="squat",fam="lunge-variations",dr=2,eq=["bodyweight"],
    ps=True,roles=["main"],goals=["build_legs","improve_performance","improve_rotation"],
    tags=["golf","hip_load","split_squat","sport_specific","power","lower_body"],
    form=["Take a golf-width stance, right foot back in a split-squat position.",
          "Lower into the split squat — feel the load shift to the right glute and hip.",
          "Hold the bottom position for 2 seconds, sensing the hip stretch.",
          "Drive up. This mimics the weight shift at the top of the backswing."],
    tips=["Lean slightly into your forward hip as you lower — simulate the address lean."],
    mistakes=["Staying upright instead of maintaining golf address tilt."],
    ts=["golf"],mt="strength",diff="beginner",struct="main",
    met=4.5,pres={"sets":3,"reps":10,"rest_seconds":45,"tempo":"slow"},rs=4.0),

dict(id="kids-ex-0172",slug="golf-wrist-hinge-drill",name="Golf Wrist Hinge Drill",
    desc="A grip-and-hinge drill using the bodyweight of the hands — training the correct wrist cock angle at the top of the backswing, which is critical for generating lag and clubhead speed without a club in hand.",
    focus="Skill",pm=["forearms"],sm=["shoulders"],st=[],
    sub=["wrist extensors","wrist flexors","forearm pronators"],
    mp="isolation",fam="golf-skill-drills",dr=1,eq=["bodyweight"],
    roles=["warmup"],goals=["improve_performance","improve_coordination"],
    tags=["golf","wrist_hinge","lag","skill","sport_specific","forearm"],
    form=["Hold both hands together as if gripping a club.",
          "Swing the imaginary club back to the 9 o'clock position.",
          "Hinge the wrists so that the lead arm is horizontal and the wrists are set at 90 degrees.",
          "Practice hinging and unhinging slowly, feeling the lever in the wrists."],
    tips=["The hinge happens naturally — don't force it. Let the swing weight cock the wrists."],
    mistakes=["Breaking the wrists too early in the takeaway — set wrists at the 9 o'clock position."],
    ts=["golf"],mt="warmup",diff="beginner",struct="warmup",
    met=2.0,pres={"sets":2,"reps":15,"rest_seconds":15,"tempo":"slow"},pr="mobility",rs=2.0),

dict(id="kids-ex-0173",slug="golf-single-leg-balance-swing",name="Golf Single-Leg Balance Swing",
    desc="A single-leg balance drill mimicking the weight transfer through the golf swing — building proprioception and dynamic balance on the lead leg through impact, the most critical balance point in the swing.",
    focus="Skill",pm=["glutes","core"],sm=["quads","calves"],st=["ankles"],
    sub=["gluteus medius","transversus abdominis","gastrocnemius"],
    mp="hold",fam="balance-drills",dr=2,eq=["bodyweight"],
    hold=True,hs=5,ps=True,roles=["main"],goals=["improve_balance","improve_performance"],
    tags=["golf","balance","weight_transfer","single_leg","sport_specific"],
    form=["Stand on your left (lead) foot. Simulate a golf swing in slow motion.",
          "As you swing through, all weight should be on the left foot by 'impact'.",
          "Hold the finish position — balanced on one foot, right heel off the ground.",
          "Hold for 5 seconds. Reset and repeat. Also practice standing on right foot for backswing."],
    tips=["A shaky finish means you need to slow down the swing — control comes before speed."],
    mistakes=["Rushing through impact — pause and feel the balance point."],
    ts=["golf"],mt="strength",diff="intermediate",struct="main",
    met=3.0,pres={"sets":3,"reps":10,"rest_seconds":30,"tempo":"slow"},rs=6.0),

dict(id="kids-ex-0174",slug="golf-deadbug-rotation",name="Golf Dead Bug Rotation",
    desc="A floor-based dead bug drill with a rotational component — extending one arm and opposite leg while rotating the torso, building the anti-rotation core stability that allows the golf swing to transfer force without energy leaks.",
    focus="Strength",pm=["core"],sm=["glutes","shoulders"],st=[],
    sub=["transversus abdominis","obliques","multifidus"],
    mp="anti_extension",fam="core-stability",dr=2,eq=["bodyweight"],
    ps=True,roles=["main"],goals=["build_core","improve_performance","injury_prevention"],
    tags=["golf","core","dead_bug","anti_rotation","sport_specific","lower_back"],
    form=["Lie on your back, arms straight up, knees at 90 degrees in tabletop.",
          "Lower your right arm back and extend your left leg simultaneously.",
          "As you lower, allow a slight trunk rotation to the right.",
          "Return to start. Alternate sides for all reps."],
    tips=["Keep the lower back pressed to the floor throughout — no arch."],
    mistakes=["Letting the lower back peel off the floor — this defeats the purpose."],
    ts=["golf","baseball","tennis"],mt="strength",diff="intermediate",struct="main",
    met=3.5,pres={"sets":3,"reps":10,"rest_seconds":45,"tempo":"slow"},rs=4.0),

dict(id="kids-ex-0175",slug="golf-hip-external-rotation-stretch",name="Golf Hip External Rotation Stretch",
    desc="A figure-4 or pigeon-style external hip rotation stretch — addressing the hip mobility limitation that restricts backswing turn and causes lower back compensation in junior golfers.",
    focus="Flexibility",pm=["glutes","hip_flexors"],sm=["adductors"],st=[],
    sub=["piriformis","gluteus minimus","hip external rotators"],
    mp="mobility",fam="hip-mobility",dr=1,eq=["bodyweight"],
    hold=True,hs=30,ps=True,roles=["warmup"],goals=["improve_mobility","improve_rotation","injury_prevention"],
    tags=["golf","hip_mobility","external_rotation","flexibility","warmup"],
    form=["Lie on your back. Cross your right ankle over your left knee (figure 4).",
          "Clasp behind your left thigh and pull both legs toward your chest.",
          "Feel the stretch deep in the right hip and glute.",
          "Hold for 30 seconds. Switch sides."],
    tips=["The closer the left thigh comes to the chest, the deeper the stretch."],
    mistakes=["Letting the lower back round off the floor — keep it flat."],
    ts=["golf","tennis","running","soccer"],mt="warmup",diff="beginner",struct="warmup",
    met=2.0,pres={"sets":2,"duration_seconds":30,"rest_seconds":15,"tempo":"static"},pr="mobility",rs=30.0),

dict(id="kids-ex-0176",slug="golf-shoulder-turn-drill",name="Golf Shoulder Turn Drill",
    desc="A standing shoulder turn drill with arms crossed over the chest — maximising the shoulder turn angle relative to the hips (X-factor), the key predictor of driving distance in young golfers.",
    focus="Mobility",pm=["back","shoulders"],sm=["core","glutes"],st=[],
    sub=["thoracic rotators","posterior deltoid","rhomboids"],
    mp="rotation",fam="golf-skill-drills",dr=1,eq=["bodyweight"],
    roles=["warmup"],goals=["improve_rotation","improve_mobility","improve_performance"],
    tags=["golf","x_factor","shoulder_turn","backswing","sport_specific","warmup"],
    form=["Stand in golf address posture, arms crossed over chest.",
          "Turn your lead shoulder to point at the ground — aim for 90-degree shoulder turn.",
          "Keep hips turning minimally — maximise the X-factor stretch between hips and shoulders.",
          "Return to address. Repeat slowly."],
    tips=["Try to point your lead shoulder at the ball position — that is a full turn."],
    mistakes=["Turning hips and shoulders together — restrict the hips to amplify the X-factor."],
    ts=["golf","baseball"],mt="warmup",diff="beginner",struct="warmup",
    met=2.5,pres={"sets":2,"reps":15,"rest_seconds":15,"tempo":"slow"},pr="mobility",rs=3.0),

dict(id="kids-ex-0177",slug="golf-impact-wall-drill",name="Golf Impact Position Wall Drill",
    desc="A static drill pressing the lead hip into a wall while simulating the impact position — teaching the hip bump and clearing pattern that initiates the downswing and prevents early extension in young golfers.",
    focus="Skill",pm=["glutes","core"],sm=["quads","back"],st=["calves"],
    sub=["gluteus maximus","obliques","quadriceps"],
    mp="rotation",fam="golf-skill-drills",dr=2,eq=["bodyweight"],
    hold=True,hs=10,roles=["warmup"],goals=["improve_performance","improve_coordination"],
    tags=["golf","impact","hip_bump","downswing","sport_specific","skill","wall_drill"],
    form=["Stand one fist-width from a wall, leading hip toward it.",
          "Bump your lead hip into the wall — this is the downswing trigger.",
          "As the hip touches, rotate your torso through to face the target.",
          "Hold the impact position for 10 seconds: lead hip at wall, weight forward, chest to target."],
    tips=["The hip moves toward the target first — then the shoulders follow, not simultaneous."],
    mistakes=["Rotating shoulders before moving the hip — the hip leads."],
    ts=["golf"],mt="warmup",diff="intermediate",struct="warmup",
    met=2.0,pres={"sets":3,"reps":10,"rest_seconds":20,"tempo":"slow"},pr="mobility",rs=12.0),

dict(id="kids-ex-0178",slug="golf-glute-bridge-hold",name="Golf Glute Bridge Hold",
    desc="A sustained isometric glute bridge — building the gluteal endurance needed to maintain consistent posture and hip drive through 18 holes, directly addressing the posterior chain weakness common in junior golfers.",
    focus="Strength",pm=["glutes"],sm=["hamstrings","core"],st=["back"],
    sub=["gluteus maximus","hamstring proximal","erector spinae"],
    mp="hip_extension",fam="glute-bridges",dr=1,eq=["bodyweight"],
    hold=True,hs=30,roles=["main"],goals=["build_glutes","improve_performance","improve_endurance"],
    tags=["golf","glutes","isometric","endurance","posterior_chain","core"],
    form=["Lie on your back, knees bent, feet flat on the floor.",
          "Drive hips up to a full bridge, squeezing glutes hard.",
          "Hold for 30 seconds — do not let hips sag.",
          "Lower slowly."],
    tips=["Tuck your chin to your chest and brace the core throughout the hold."],
    mistakes=["Hips sagging halfway through — fight to maintain height."],
    ts=["golf","running","soccer"],mt="strength",diff="beginner",struct="main",
    met=3.5,pres={"sets":3,"duration_seconds":30,"rest_seconds":30,"tempo":"static"},pr="strength",rs=30.0),

dict(id="kids-ex-0179",slug="golf-anti-sway-lateral-drill",name="Golf Anti-Sway Lateral Drill",
    desc="A lateral stability drill where athletes resist shifting their weight off the trail foot during the backswing — a wall or band provides feedback to eliminate the lateral sway that robs young golfers of power.",
    focus="Skill",pm=["glutes","core"],sm=["quads","adductors"],st=["calves"],
    sub=["gluteus medius","obliques","adductors"],
    mp="anti_extension",fam="golf-skill-drills",dr=2,eq=["bodyweight"],
    ps=True,roles=["main"],goals=["improve_performance","improve_balance","improve_rotation"],
    tags=["golf","anti_sway","backswing","weight_shift","sport_specific","lateral_stability"],
    form=["Stand with your trail hip lightly touching a wall or post.",
          "Simulate your backswing while resisting any lateral push into the wall.",
          "The hip should rotate around a stable axis — not push outward.",
          "If you feel wall pressure, you are swaying — fix the rotation."],
    tips=["The feeling should be 'rotating INTO the hip' not 'moving ONTO the hip'."],
    mistakes=["Pushing the hip outward into the wall — rotate, don't sway."],
    ts=["golf"],mt="strength",diff="intermediate",struct="main",
    met=3.0,pres={"sets":3,"reps":15,"rest_seconds":30,"tempo":"controlled"},pr="skill",rs=3.0),

dict(id="kids-ex-0180",slug="golf-wrist-radial-deviation-drill",name="Golf Wrist Radial Deviation Drill",
    desc="A forearm and wrist mobility drill practising the radial deviation (wrist hinge toward thumb) required at the top of the golf backswing — often overlooked as a limiter of clean wrist set in junior golfers.",
    focus="Flexibility",pm=["forearms"],sm=["shoulders"],st=[],
    sub=["wrist extensors","radial deviators","extensor carpi radialis"],
    mp="isolation",fam="golf-skill-drills",dr=1,eq=["bodyweight"],
    ps=True,roles=["warmup"],goals=["improve_mobility","improve_performance"],
    tags=["golf","wrist","forearm","mobility","flexibility","warmup"],
    form=["Hold your right arm out horizontally with palm facing down.",
          "Hinge the hand upward (toward the ceiling) — this is radial deviation.",
          "Lower back to neutral.",
          "Do 15 slow reps each hand."],
    tips=["Keep the forearm still — only the wrist moves."],
    mistakes=["Rotating the forearm instead of purely deviating the wrist."],
    ts=["golf","tennis","baseball"],mt="warmup",diff="beginner",struct="warmup",
    met=2.0,pres={"sets":2,"reps":15,"rest_seconds":10,"tempo":"slow"},pr="mobility",rs=2.0),

# ── TENNIS (12) ──────────────────────────────────────────────────────────────
dict(id="kids-ex-0181",slug="tennis-split-step-drill",name="Tennis Split Step Drill",
    desc="The tennis split step — a small two-foot hop timed to the opponent's contact — is the most fundamental reactive footwork move in tennis. This drill trains the timing and landing mechanics through repetition.",
    focus="Skill",pm=["calves","quads"],sm=["glutes","core"],st=["ankles"],
    sub=["gastrocnemius","vastus lateralis","soleus"],
    mp="locomotion",fam="tennis-footwork",dr=1,eq=["bodyweight"],
    roles=["warmup"],goals=["improve_agility","improve_coordination","improve_performance"],
    tags=["tennis","split_step","footwork","reactive","sport_specific","warmup"],
    form=["Stand in ready position — athletic stance, weight on balls of feet.",
          "As a coach says 'now' (or you count), hop into a small two-foot split step.",
          "Land softly on the balls of both feet simultaneously.",
          "Immediately push off to the right or left as directed."],
    tips=["Land ready to move — never flat-footed. Stay on your toes."],
    mistakes=["Landing flat-footed or with stiff knees — absorb the landing with soft joints."],
    ts=["tennis"],mt="warmup",diff="beginner",struct="warmup",
    met=4.0,pres={"sets":3,"reps":20,"rest_seconds":20,"tempo":"fast"},rs=0.5),

dict(id="kids-ex-0182",slug="tennis-groundstroke-rotation-drill",name="Tennis Groundstroke Rotation Drill",
    desc="A bodyweight rotation drill mimicking the shoulder and hip coil-and-uncoil sequence of a forehand or backhand groundstroke — training kinetic chain sequencing for groundstroke power without a racket.",
    focus="Skill",pm=["core","shoulders"],sm=["glutes","back","quads"],st=[],
    sub=["obliques","anterior deltoid","hip rotators"],
    mp="rotation",fam="rotational-core",dr=2,eq=["bodyweight"],
    ps=True,roles=["main"],goals=["improve_rotation","improve_performance","improve_coordination"],
    tags=["tennis","groundstroke","rotation","kinetic_chain","sport_specific","forehand"],
    form=["Stand sideways (forehand side) with weight on your right foot.",
          "Coil your shoulders and hips right (load phase).",
          "Uncoil: shift weight to the left foot, hips lead, then shoulders, then arm extension.",
          "Finish with your right shoulder pointing toward the target. Switch to backhand side."],
    tips=["Hips must rotate BEFORE shoulders — the sequence is hips → trunk → arm."],
    mistakes=["Hitting with the arm only, without hip rotation — the stroke has no power."],
    ts=["tennis","golf","baseball"],mt="strength",diff="intermediate",struct="main",
    met=4.5,pres={"sets":3,"reps":12,"rest_seconds":45,"tempo":"controlled"},rs=3.0),

dict(id="kids-ex-0183",slug="tennis-service-trophy-pose-hold",name="Tennis Service Trophy Pose Hold",
    desc="An isometric hold of the tennis service 'trophy pose' — the maximum external rotation of the hitting arm before pronation — building shoulder and rotator cuff endurance critical for serve velocity and injury prevention.",
    focus="Strength",pm=["shoulders"],sm=["core","back"],st=["wrists","triceps"],
    sub=["infraspinatus","teres minor","external rotators"],
    mp="hold",fam="tennis-serve-drills",dr=2,eq=["bodyweight"],
    hold=True,hs=10,ps=True,roles=["main"],goals=["build_shoulders","improve_performance","injury_prevention"],
    tags=["tennis","serve","trophy_pose","external_rotation","shoulder_strength","sport_specific"],
    form=["Stand and raise both arms: right arm bent and cocked up (elbow high, hand at ear).",
          "Left arm extended upward (non-dominant arm in classic serve trophy pose).",
          "Maintain this position with the right shoulder in maximum external rotation.",
          "Hold for 10 seconds. Switch to simulate a left-hand serve."],
    tips=["Squeeze the shoulder blade back and down to keep the shoulder in the socket."],
    mistakes=["Letting the elbow drop — elbow must stay level with or above the shoulder."],
    ts=["tennis","baseball"],mt="strength",diff="intermediate",struct="main",
    met=3.0,pres={"sets":3,"duration_seconds":10,"rest_seconds":30,"tempo":"static"},rs=10.0),

dict(id="kids-ex-0184",slug="tennis-lateral-shuffle-cone",name="Tennis Lateral Shuffle Drill",
    desc="A side-to-side shuffling sprint covering 3–5 metres between cones — the primary court coverage movement in tennis, training lateral speed, change-of-direction mechanics, and the split step return pattern.",
    focus="Cardio",pm=["quads","glutes","calves"],sm=["hamstrings","core","adductors"],st=["ankles"],
    sub=["vastus lateralis","gluteus medius","gastrocnemius"],
    mp="locomotion",fam="lateral-agility",dr=2,eq=["bodyweight"],
    roles=["main","warmup"],goals=["improve_agility","improve_speed","improve_performance"],
    tags=["tennis","lateral","shuffle","footwork","agility","court","sport_specific"],
    form=["Set two cones 3–5 metres apart. Start at the right cone in athletic stance.",
          "Shuffle laterally to the left cone — don't cross your feet.",
          "Touch the left cone, do a split step, then shuffle right back.",
          "Keep weight on the balls of your feet throughout. 30 seconds maximum speed."],
    tips=["Push off the outside foot to change direction — plant, split step, push."],
    mistakes=["Crossing feet in the shuffle — maintain the side-step pattern."],
    ts=["tennis","basketball","soccer"],mt="cardio",diff="beginner",struct="main",
    met=8.0,pres={"sets":4,"duration_seconds":30,"rest_seconds":30,"tempo":"fast"},rs=None),

dict(id="kids-ex-0185",slug="tennis-overhead-reach-stretch",name="Tennis Overhead Reach Stretch",
    desc="A dynamic overhead reach pattern — reaching one arm high and rotating toward it — warming up the rotator cuff, lats, and shoulder girdle for the serve and overhead patterns used throughout a tennis match.",
    focus="Mobility",pm=["shoulders","back"],sm=["core"],st=[],
    sub=["latissimus dorsi","posterior deltoid","thoracic extensors"],
    mp="mobility",fam="shoulder-mobility",dr=1,eq=["bodyweight"],
    ps=True,roles=["warmup"],goals=["improve_mobility","injury_prevention","warmup"],
    tags=["tennis","overhead","shoulder","mobility","warmup","serve","sport_specific"],
    form=["Stand tall. Reach your right arm straight overhead as high as possible.",
          "As you reach, rotate your torso slightly right and look up at your hand.",
          "Lower and reach with the left arm. Alternate for all reps.",
          "Add a slight lateral lean toward the reaching arm for a lat stretch."],
    tips=["Think of trying to touch the ceiling — elongate the whole side of your body."],
    mistakes=["Shrugging the shoulder — keep it packed as you reach."],
    ts=["tennis","baseball","basketball"],mt="warmup",diff="beginner",struct="warmup",
    met=2.5,pres={"sets":2,"reps":15,"rest_seconds":15,"tempo":"slow"},pr="mobility",rs=2.5),

dict(id="kids-ex-0186",slug="tennis-forearm-roller-drill",name="Tennis Forearm Supination Drill",
    desc="A forearm pronation/supination drill holding a light dumbbell (or water bottle) — building the forearm rotators critical for topspin production and pronation through the tennis serve, preventing elbow overuse injuries.",
    focus="Strength",pm=["forearms"],sm=["wrists","shoulders"],st=[],
    sub=["supinator","pronator teres","brachioradialis"],
    mp="isolation",fam="forearm-exercises",dr=1,eq=["dumbbell"],
    ps=True,roles=["main"],goals=["build_forearm","injury_prevention","improve_performance"],
    tags=["tennis","forearm","pronation","supination","serve","elbow_health","sport_specific"],
    form=["Hold a light dumbbell with one hand, arm resting on a thigh, elbow at 90 degrees.",
          "Rotate palm to face the ceiling (supination). Then rotate palm to face the floor (pronation).",
          "Move slowly through the full range.",
          "15 reps per direction, each arm."],
    tips=["Use a very light weight — this is an endurance/injury prevention drill, not a max-effort lift."],
    mistakes=["Rotating the shoulder instead of the forearm — keep the elbow on the thigh."],
    ts=["tennis","baseball","golf"],mt="strength",diff="beginner",struct="main",
    met=3.0,pres={"sets":2,"reps":15,"rest_seconds":20,"tempo":"slow"},rs=3.0),

dict(id="kids-ex-0187",slug="tennis-volley-ready-position",name="Tennis Volley Ready Position Drill",
    desc="A dynamic drill holding the volley ready position and reacting to imaginary ball direction — training the split-step and compact volley punch while building the hip and shoulder stability needed at the net.",
    focus="Skill",pm=["quads","core"],sm=["glutes","shoulders"],st=["calves","ankles"],
    sub=["vastus lateralis","obliques","anterior deltoid"],
    mp="hold",fam="tennis-footwork",dr=2,eq=["bodyweight"],
    roles=["warmup","main"],goals=["improve_coordination","improve_agility","improve_performance"],
    tags=["tennis","volley","net","footwork","sport_specific","skill","reactive"],
    form=["Stand in net-volley position: athletic stance, non-dominant hand in front as if holding a throat.",
          "React to a coach's call of 'right' or 'left' — take one step and punch a compact volley.",
          "Return to volley ready position immediately.",
          "20 reps total — 10 each side."],
    tips=["The volley punch is short and compact — not a full swing."],
    mistakes=["Taking a big backswing — volleys are blocked, not swung."],
    ts=["tennis"],mt="warmup",diff="intermediate",struct="warmup",
    met=4.5,pres={"sets":3,"reps":20,"rest_seconds":30,"tempo":"fast"},rs=1.0),

dict(id="kids-ex-0188",slug="tennis-shoulder-external-rotation-stretch",name="Tennis Shoulder External Rotation Stretch",
    desc="A doorway or arms-behind-back shoulder stretch targeting the anterior capsule and internal rotators — counterbalancing the extreme internal rotation load of the tennis serve to maintain shoulder health.",
    focus="Flexibility",pm=["shoulders","chest"],sm=["back"],st=[],
    sub=["anterior capsule","subscapularis","pectoralis minor"],
    mp="mobility",fam="shoulder-mobility",dr=1,eq=["bodyweight"],
    hold=True,hs=30,ps=True,roles=["warmup"],goals=["improve_mobility","injury_prevention"],
    tags=["tennis","shoulder","external_rotation_stretch","flexibility","warmup","serve"],
    form=["Stand in a doorway. Place your right forearm along the door frame at shoulder height.",
          "Lean your body forward until you feel a gentle stretch in the front of the shoulder and chest.",
          "Hold for 30 seconds. Do both sides."],
    tips=["Position the arm at different heights (high, mid, low) to stretch different parts of the chest."],
    mistakes=["Leaning too aggressively — a gentle sustained stretch is more effective than a deep painful one."],
    ts=["tennis","baseball","swimming"],mt="warmup",diff="beginner",struct="warmup",
    met=2.0,pres={"sets":2,"duration_seconds":30,"rest_seconds":15,"tempo":"static"},pr="mobility",rs=30.0),

dict(id="kids-ex-0189",slug="tennis-reaction-ball-drop",name="Tennis Ball Drop Reaction Drill",
    desc="A partner reaction drill where one player drops a ball from shoulder height and the other catches it before the second bounce — sharpening the visual reaction, foot speed, and split-step timing central to tennis.",
    focus="Cardio",pm=["calves","quads"],sm=["glutes","core"],st=["ankles"],
    sub=["gastrocnemius","vastus lateralis","gluteus medius"],
    mp="locomotion",fam="tennis-footwork",dr=2,eq=["bodyweight"],
    roles=["main"],goals=["improve_agility","improve_coordination","improve_performance"],
    tags=["tennis","reaction","agility","footwork","sport_specific","partner_drill","fun"],
    form=["Stand 2 metres from your partner. They hold a tennis ball at shoulder height.",
          "The moment they release it (without warning), explode forward and catch it before the second bounce.",
          "Return to position. Vary the timing to train true reaction, not anticipation.",
          "20 reps each."],
    tips=["Stay on the balls of your feet — flat-footed athletes always catch it late."],
    mistakes=["Anticipating the drop and moving early — wait for visual cue."],
    ts=["tennis","basketball","soccer"],mt="cardio",diff="intermediate",struct="main",
    met=7.0,pres={"sets":4,"reps":10,"rest_seconds":30,"tempo":"fast"},rs=2.0),

dict(id="kids-ex-0190",slug="tennis-core-bracing-row",name="Tennis Core Anti-Rotation Row",
    desc="A unilateral cable or band row with specific emphasis on maintaining hip square alignment — training the rotational stability and core pre-tension required before and during every tennis groundstroke.",
    focus="Strength",pm=["core","back"],sm=["shoulders","biceps"],st=["quads","glutes"],
    sub=["obliques","rhomboids","latissimus dorsi"],
    mp="pull_horizontal",fam="anti-rotation-core",dr=3,eq=["bands"],
    ps=True,roles=["main"],goals=["build_core","build_back","improve_performance"],
    tags=["tennis","anti_rotation","core","row","sport_specific","stability"],
    form=["Anchor band at chest height. Stand sideways to it, feet shoulder-width.",
          "Hold one end with the far hand, arm extended toward the anchor.",
          "Row toward your ribcage while keeping your hips perfectly square to the front.",
          "Lower slowly. Complete all reps then switch sides."],
    tips=["Brace the core as if bracing for a punch before you begin the row."],
    mistakes=["Rotating the hips as you pull — hips must face forward the entire set."],
    ts=["tennis","golf","baseball"],mt="strength",diff="intermediate",struct="main",
    met=4.5,pres={"sets":3,"reps":10,"rest_seconds":45,"tempo":"controlled"},rs=4.0),

dict(id="kids-ex-0191",slug="tennis-calf-raise-toe-tap",name="Tennis Calf Raise and Toe Tap",
    desc="A calf raise immediately followed by a rapid toe tap — building the elastic calf and foot stiffness needed for explosive split-step rebounds on hard courts, reducing the foot fatigue that affects court speed late in matches.",
    focus="Strength",pm=["calves"],sm=["ankles","quads"],st=["core"],
    sub=["gastrocnemius","soleus","tibialis anterior"],
    mp="isolation",fam="calf-raises",dr=2,eq=["bodyweight"],
    roles=["warmup","main"],goals=["build_calves","improve_agility","improve_performance"],
    tags=["tennis","calves","elastic","split_step","footwork","sport_specific","plyometric"],
    form=["Stand on the edge of a step or flat ground. Rise onto toes (calf raise) as high as possible.",
          "Lower to the start. Immediately tap your toes on the floor 5 times — fast and light.",
          "That is one rep. The toe taps train the tendon rebound.",
          "Keep ankles stiff during the taps — not floppy."],
    tips=["The toe taps should feel like you're lightly bouncing — minimal foot contact time."],
    mistakes=["Slow, heavy toe taps — the goal is rapid elastic contact, not weighted steps."],
    ts=["tennis","basketball","running"],mt="strength",diff="intermediate",struct="main",
    met=5.0,pres={"sets":3,"reps":10,"rest_seconds":45,"tempo":"fast"},rs=2.0),

dict(id="kids-ex-0192",slug="tennis-shadow-swing-warmup",name="Tennis Shadow Swing Warm-Up",
    desc="A full shadow-swing sequence — forehand, backhand, overhead, volley — performed at 50% speed to progressively warm up the rotator cuff, shoulder girdle, and core rotation patterns before picking up a racket.",
    focus="Skill",pm=["shoulders","core"],sm=["back","glutes","triceps"],st=[],
    sub=["rotator cuff","anterior deltoid","obliques"],
    mp="rotation",fam="tennis-skill-drills",dr=1,eq=["bodyweight"],
    roles=["warmup"],goals=["warmup","improve_coordination","injury_prevention"],
    tags=["tennis","shadow_swing","warmup","sport_specific","rotator_cuff","skill"],
    form=["Without a racket: simulate a forehand swing at 50% speed (load, rotate, follow through).",
          "Simulate a backhand swing, both one-handed and two-handed versions.",
          "Simulate an overhead smash — reach high and pronate.",
          "Simulate a forehand volley punch.  5 reps of each stroke."],
    tips=["Focus on the rotation sequence, not the swing — hips lead on every stroke."],
    mistakes=["Swinging only with the arms — include full hip-to-shoulder rotation."],
    ts=["tennis"],mt="warmup",diff="beginner",struct="warmup",
    met=3.0,pres={"sets":2,"reps":5,"rest_seconds":20,"tempo":"slow"},pr="mobility",rs=4.0),

# ── SOCCER (12) ──────────────────────────────────────────────────────────────
dict(id="kids-ex-0193",slug="soccer-cruyff-turn-drill",name="Soccer Cruyff Turn Drill",
    desc="A technical drill practising the Cruyff Turn — feinting a pass or cross then dragging the ball behind the standing foot and spinning away — building first-touch decision speed and change-of-direction skill.",
    focus="Skill",pm=["quads","glutes"],sm=["calves","core","adductors"],st=["ankles"],
    sub=["vastus lateralis","gluteus medius","gastrocnemius"],
    mp="locomotion",fam="soccer-footwork",dr=2,eq=["bodyweight"],
    roles=["main"],goals=["improve_agility","improve_coordination","improve_performance"],
    tags=["soccer","cruyff_turn","1v1","change_of_direction","skill","sport_specific"],
    form=["Approach a cone as if about to pass to the right.",
          "Plant the right foot next to the ball. Fake the pass left.",
          "Drag the ball behind the right foot with the inside of your left foot.",
          "Spin right (180 degrees) and accelerate away in the new direction."],
    tips=["The key is the selling of the fake — commit to the pass motion before reversing."],
    mistakes=["Not selling the fake — if you go straight to the drag, it's easy to read."],
    ts=["soccer"],mt="cardio",diff="intermediate",struct="main",
    met=7.0,pres={"sets":4,"reps":10,"rest_seconds":30,"tempo":"fast"},rs=2.0),

dict(id="kids-ex-0194",slug="soccer-dynamic-leg-swing",name="Soccer Dynamic Leg Swing",
    desc="Forward-backward and side-to-side dynamic leg swings — the standard pre-training hip mobility drill for soccer players, opening the hip flexors, hamstrings, and adductors before sprinting, kicking, and agility work.",
    focus="Mobility",pm=["hip_flexors","hamstrings"],sm=["glutes","adductors"],st=["core"],
    sub=["hip flexors","biceps femoris","adductors"],
    mp="mobility",fam="dynamic-stretches",dr=1,eq=["bodyweight"],
    ps=True,roles=["warmup"],goals=["improve_mobility","warmup","injury_prevention"],
    tags=["soccer","dynamic_stretch","hip","leg_swing","warmup","sport_specific"],
    form=["Hold a wall or post for balance. Swing the right leg forward and back, gradually increasing range. 20 times.",
          "Swing the same leg side to side across the body. 20 times.",
          "Switch to the left leg."],
    tips=["Increase range gradually over the 20 reps — don't force full range on rep 1."],
    mistakes=["Forcing the range on the first rep — this is a warmup, not a stretch."],
    ts=["soccer","football","running","basketball"],mt="warmup",diff="beginner",struct="warmup",
    met=2.5,pres={"sets":1,"reps":20,"rest_seconds":10,"tempo":"slow"},pr="mobility",rs=1.5),

dict(id="kids-ex-0195",slug="soccer-small-sided-dribble-sprint",name="Soccer Dribble and Sprint",
    desc="A 20-metre dribble sprint at full speed — combining ball manipulation with maximum linear acceleration to train the coordination of touch and stride rate essential for breaking into space behind a defence.",
    focus="Cardio",pm=["quads","calves","glutes"],sm=["hamstrings","core","hip_flexors"],st=["ankles"],
    sub=["quadriceps","gastrocnemius","gluteus maximus"],
    mp="locomotion",fam="soccer-footwork",dr=2,eq=["bodyweight"],
    roles=["main"],goals=["improve_speed","improve_coordination","improve_performance"],
    tags=["soccer","sprint","dribble","acceleration","speed","sport_specific"],
    form=["Start stationary with a ball. On a signal, push the ball forward with your laces.",
          "Take two normal running strides, then nudge the ball again.",
          "Maintain a touch every 2–3 strides at full sprint pace.",
          "Sprint the full 20 m then jog back."],
    tips=["Keep touches ahead of your body — a short touch kills your stride."],
    mistakes=["Looking at the ball — look up and use peripheral vision for ball contact."],
    ts=["soccer"],mt="cardio",diff="intermediate",struct="main",
    met=9.0,pres={"sets":5,"reps":1,"rest_seconds":45,"tempo":"fast"},rs=4.0),

dict(id="kids-ex-0196",slug="soccer-defensive-shuffle-close",name="Soccer Defensive Shuffle and Close",
    desc="A defensive sliding drill where athletes shuffle laterally to close down an imaginary attacker — training the angled approach, body angle, and last-step jockey position required to contain 1-v-1 in defence.",
    focus="Cardio",pm=["glutes","quads","adductors"],sm=["calves","hamstrings","core"],st=["ankles"],
    sub=["gluteus medius","adductors","vastus lateralis"],
    mp="locomotion",fam="lateral-agility",dr=2,eq=["bodyweight"],
    roles=["main"],goals=["improve_agility","improve_speed","improve_performance"],
    tags=["soccer","defence","shuffle","1v1","closing_speed","sport_specific"],
    form=["Start 5 metres from a cone. Shuffle sideways at 45 degrees toward it.",
          "At the cone, plant and jockey (small bouncing shuffle) for 3 seconds.",
          "Shuffle back and return to start.",
          "Repeat 10 times each direction."],
    tips=["Keep low throughout — a defender who stands up straight loses the sprint."],
    mistakes=["Crossing feet during the shuffle — stay laterally oriented."],
    ts=["soccer","basketball"],mt="cardio",diff="beginner",struct="main",
    met=7.0,pres={"sets":3,"reps":10,"rest_seconds":30,"tempo":"fast"},rs=4.0),

dict(id="kids-ex-0197",slug="soccer-hip-flexor-stretch-kneeling",name="Soccer Kneeling Hip Flexor Stretch",
    desc="A kneeling lunge hip flexor stretch — the most critical recovery drill for soccer players, countering the hip flexor tightness from sprinting, kicking, and extended upright running that causes lower back and hamstring problems.",
    focus="Flexibility",pm=["hip_flexors"],sm=["quads","core"],st=[],
    sub=["iliopsoas","rectus femoris","tensor fasciae latae"],
    mp="mobility",fam="hip-flexibility",dr=1,eq=["bodyweight"],
    hold=True,hs=30,ps=True,roles=["warmup"],goals=["improve_mobility","injury_prevention","warmup"],
    tags=["soccer","hip_flexor","stretch","flexibility","recovery","warmup","sport_specific"],
    form=["Kneel on the right knee. Left foot flat in front, left knee at 90 degrees.",
          "Tuck the pelvis under (posterior pelvic tilt) — this engages the stretch.",
          "Shift your weight forward until you feel a stretch at the front of the right hip.",
          "Hold for 30 seconds. Switch sides."],
    tips=["Squeeze the right glute as you stretch — this deepens the hip flexor release."],
    mistakes=["Arching the lower back — tuck the pelvis first to isolate the hip flexor."],
    ts=["soccer","football","running","basketball"],mt="warmup",diff="beginner",struct="warmup",
    met=2.0,pres={"sets":2,"duration_seconds":30,"rest_seconds":15,"tempo":"static"},pr="mobility",rs=30.0),

dict(id="kids-ex-0198",slug="soccer-heading-approach-jump",name="Soccer Heading Jump Approach",
    desc="A technical jump drill practising the 3-step approach and two-foot takeoff for heading — developing the timing, explosive jump, and core tension required to head the ball powerfully and safely.",
    focus="Skill",pm=["quads","glutes","calves"],sm=["hamstrings","core"],st=["ankles"],
    sub=["quadriceps","gastrocnemius","gluteus maximus"],
    mp="jump",fam="jump-training",dr=2,eq=["bodyweight"],
    roles=["main"],goals=["improve_vertical","improve_coordination","improve_performance"],
    tags=["soccer","heading","jump","aerial","approach","sport_specific","technical"],
    form=["Take 3 run-up strides toward the jump point.",
          "Plant both feet and jump explosively — drive the arms and snap the hips forward.",
          "At the peak, simulate a heading action — forward neck snap.",
          "Land softly on both feet with knees bent."],
    tips=["Time the jump so you contact the ball at the peak, not on the way down."],
    mistakes=["Single-leg takeoff — a two-foot takeoff gives more controlled power."],
    ts=["soccer","basketball","football"],mt="strength",diff="intermediate",struct="main",
    met=6.0,pres={"sets":4,"reps":8,"rest_seconds":45,"tempo":"fast"},rs=3.0),

dict(id="kids-ex-0199",slug="soccer-adductor-squeeze",name="Soccer Adductor Squeeze Drill",
    desc="A lying isometric adductor squeeze using a ball or folded towel between the knees — building the groin/adductor strength that prevents the groin strains endemic in soccer players who kick with force repeatedly.",
    focus="Strength",pm=["adductors"],sm=["core","glutes"],st=[],
    sub=["adductor longus","adductor magnus","gracilis"],
    mp="isolation",fam="adductor-exercises",dr=1,eq=["bodyweight"],
    hold=True,hs=5,roles=["main"],goals=["injury_prevention","build_legs","improve_performance"],
    tags=["soccer","adductors","groin","injury_prevention","isometric","sport_specific"],
    form=["Lie on your back, knees bent, feet flat. Place a folded towel or small ball between your knees.",
          "Squeeze the knees together as hard as possible against the object.",
          "Hold for 5 seconds. Release slowly.",
          "10 reps."],
    tips=["Imagine you're trying to crush the object between your knees."],
    mistakes=["Squeezing weakly — full effort isometrics are the most effective here."],
    ts=["soccer","football","basketball"],mt="strength",diff="beginner",struct="main",
    met=3.0,pres={"sets":3,"reps":10,"rest_seconds":30,"tempo":"static"},rs=5.0),

dict(id="kids-ex-0200",slug="soccer-change-of-direction-5-10-5",name="Soccer 5-10-5 Agility Drill",
    desc="The soccer version of the 5-10-5 agility shuttle — sprinting 5 yards right, then 10 yards left, then 5 yards back right — the gold-standard test and training drill for change-of-direction speed on the soccer field.",
    focus="Cardio",pm=["quads","glutes","calves"],sm=["hamstrings","adductors","core"],st=["ankles"],
    sub=["vastus lateralis","gluteus maximus","gastrocnemius"],
    mp="locomotion",fam="agility-drills",dr=3,eq=["bodyweight"],
    roles=["main"],goals=["improve_agility","improve_speed","improve_performance"],
    tags=["soccer","agility","5-10-5","change_of_direction","speed","sport_specific","shuttle"],
    form=["Set 3 cones in a line: 5 yards apart each. Start at the centre cone.",
          "Sprint 5 yards to the right cone. Touch it.",
          "Sprint 10 yards to the left cone. Touch it.",
          "Sprint 5 yards back to the centre cone."],
    tips=["Plant the outside foot hard at each cone — your cut should be explosive, not gradual."],
    mistakes=["Running past the cone and looping back — the touch and cut should be crisp."],
    ts=["soccer","basketball","football"],mt="cardio",diff="intermediate",struct="main",
    met=9.0,pres={"sets":5,"reps":1,"rest_seconds":60,"tempo":"fast"},rs=6.0),

dict(id="kids-ex-0201",slug="soccer-ankle-roll-prevention",name="Soccer Ankle Stability Drill",
    desc="A single-leg balance progression on unstable ground — building the proprioceptive ankle stability that prevents the inversion sprains that sideline soccer players more than any other injury.",
    focus="Strength",pm=["calves","ankles"],sm=["quads","glutes","core"],st=[],
    sub=["peroneals","tibialis anterior","gastrocnemius"],
    mp="hold",fam="balance-drills",dr=2,eq=["bodyweight"],
    hold=True,hs=30,ps=True,roles=["main"],goals=["injury_prevention","improve_balance","improve_performance"],
    tags=["soccer","ankle","proprioception","balance","injury_prevention","stability","sport_specific"],
    form=["Stand on your right foot on a folded mat or firm pillow. Close your eyes.",
          "Hold the balance for 30 seconds without touching down.",
          "Progress: eyes closed → pass a ball between hands → catch thrown balls.",
          "Switch to the left foot."],
    tips=["Slight knee bend (not locked) dramatically improves balance."],
    mistakes=["Looking at the floor — challenge yourself with eyes straight ahead or closed."],
    ts=["soccer","basketball","running","football"],mt="strength",diff="beginner",struct="main",
    met=3.0,pres={"sets":3,"duration_seconds":30,"rest_seconds":20,"tempo":"static"},rs=30.0),

dict(id="kids-ex-0202",slug="soccer-stutter-step-acceleration",name="Soccer Stutter Step Acceleration",
    desc="A stutter-step and explode drill — taking 4–6 very rapid short steps in place then bursting forward — training the rapid weight shift and first-step quickness used when breaking into space after reading the play.",
    focus="Cardio",pm=["calves","quads","hip_flexors"],sm=["glutes","hamstrings"],st=["ankles","core"],
    sub=["gastrocnemius","quadriceps","hip flexors"],
    mp="locomotion",fam="acceleration-drills",dr=2,eq=["bodyweight"],
    roles=["main"],goals=["improve_speed","improve_agility","improve_performance"],
    tags=["soccer","stutter_step","first_step","acceleration","quickness","sport_specific"],
    form=["Stand in athletic stance, weight on balls of feet.",
          "Take 4–6 rapid tiny steps in place (stutter steps) — very fast and light.",
          "On 'go' (a coach's call or a cone), explode into a 10-metre sprint.",
          "Jog back. Repeat with direction change calls."],
    tips=["The stutter steps keep the muscles pre-loaded — you spring instead of starting cold."],
    mistakes=["Heavy, slow stutter steps — they must be rapid and light like a boxer's bounce."],
    ts=["soccer","basketball","football"],mt="cardio",diff="intermediate",struct="main",
    met=8.0,pres={"sets":6,"reps":1,"rest_seconds":30,"tempo":"fast"},rs=5.0),

dict(id="kids-ex-0203",slug="soccer-half-volley-knee-lift",name="Soccer Half-Volley Knee Lift",
    desc="A marching high-knee drill combined with a simulated volley kick at the peak — training the hip flexor power, timing, and core stability required for half-volley and lofted passes in the air.",
    focus="Skill",pm=["hip_flexors","quads"],sm=["core","glutes","calves"],st=["ankles"],
    sub=["iliopsoas","rectus femoris","transversus abdominis"],
    mp="locomotion",fam="soccer-footwork",dr=2,eq=["bodyweight"],
    roles=["main"],goals=["improve_coordination","build_legs","improve_performance"],
    tags=["soccer","knee_lift","volley","hip_flexor","skill","sport_specific","kicking"],
    form=["March forward. At each right step, drive the left knee high.",
          "At the peak of the knee lift, simulate a volley kick — snap the foot out and down.",
          "Continue marching — alternate legs if preferred.",
          "Focus on height of the knee, not speed of the march."],
    tips=["The snap of the foot should come from the quad and hip flexor together."],
    mistakes=["Not reaching full hip flexion — the knee should reach hip height or above."],
    ts=["soccer"],mt="strength",diff="intermediate",struct="main",
    met=5.5,pres={"sets":3,"reps":12,"rest_seconds":30,"tempo":"controlled"},rs=2.5),

dict(id="kids-ex-0204",slug="soccer-wall-passing-agility",name="Soccer Wall Pass and Move Drill",
    desc="A 1-2 passing drill using a wall — passing the ball against the wall and moving laterally to receive the return — training sharp one-touch passing technique, first-touch control, and the immediate 'move after pass' habit.",
    focus="Skill",pm=["calves","quads","adductors"],sm=["glutes","core"],st=["ankles"],
    sub=["gastrocnemius","adductors","quadriceps"],
    mp="locomotion",fam="soccer-footwork",dr=2,eq=["bodyweight"],
    roles=["main"],goals=["improve_coordination","improve_agility","improve_performance"],
    tags=["soccer","passing","1-2","wall","movement","skill","sport_specific","fun"],
    form=["Stand 3 metres from a wall. Pass the ball with the inside of your right foot.",
          "Immediately take 2 shuffles to the right.",
          "Receive the return with your right or left foot — settle and pass again.",
          "Vary angle and distance. 60 touches per session."],
    tips=["Move before the ball arrives back — don't wait for it to come to you."],
    mistakes=["Standing still after the pass — in soccer you should always move after passing."],
    ts=["soccer"],mt="cardio",diff="beginner",struct="main",
    met=6.0,pres={"sets":3,"duration_seconds":60,"rest_seconds":30,"tempo":"controlled"},rs=None),
]

def main():
    with open(SRC) as f:
        data=json.load(f)
    before=len(data)
    new_exs=[ex(d) for d in DEFS]
    data.extend(new_exs)
    with open(SRC,'w') as f:
        json.dump(data,f,indent=2)
    print(f"Batch 3 done: {len(new_exs)} entries added, running total {len(data)}/500 (was {before})")

    # Final summary
    from collections import defaultdict
    kids=tweens=teens=unrestricted=0
    eq_counts=defaultdict(int)
    mt_counts=defaultdict(int)
    sport_counts=defaultdict(int)
    for ex_obj in data:
        tx=ex_obj.get('taxonomy',{})
        bands=tx.get('age_bands_suggested',[])
        if not bands:
            unrestricted+=1
        else:
            if 'Kids' in bands: kids+=1
            if 'Tweens' in bands: tweens+=1
            if 'Teens' in bands: teens+=1
        for e in ex_obj.get('equipment',[]):
            eq_counts[e]+=1
        mt=tx.get('movement_type','')
        if mt: mt_counts[mt]+=1
        for s in tx.get('sports_suggested',[]):
            sport_counts[s]+=1

    print(f"\n=== FINAL SUMMARY ===")
    print(f"Total exercises: {len(data)}")
    print(f"\nAge bands:")
    print(f"  Kids:         {kids}")
    print(f"  Tweens:       {tweens}")
    print(f"  Teens:        {teens}")
    print(f"  Unrestricted: {unrestricted}")
    print(f"\nEquipment:")
    for k,v in sorted(eq_counts.items(),key=lambda x:-x[1]):
        print(f"  {k}: {v}")
    print(f"\nMovement type:")
    for k,v in sorted(mt_counts.items(),key=lambda x:-x[1]):
        print(f"  {k}: {v}")
    print(f"\nSports suggested:")
    for k,v in sorted(sport_counts.items(),key=lambda x:-x[1]):
        print(f"  {k}: {v}")

if __name__=='__main__':
    main()
